// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This is the base request container for all Finding Service operations.
 * 
 */
public abstract class BaseFindingServiceRequest extends BestMatchFindingServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public SortOrderType sortOrder;	
	
    
}