// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Base response container for all Finding Service operations.
 * 
 */
public abstract class BaseFindingServiceResponse extends BaseServiceResponse implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public SearchResult searchResult;	
	
	@Element
	public PaginationOutput paginationOutput;	
	
	@Element
	public String itemSearchURL;	
	
	@Element
	public List<ExtensionType> extension;	
	
    
}