// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Base container for histogram information.
 * 
 */
public class CategoryHistogramContainer implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public List<CategoryHistogram> categoryHistogram;	
	
	@Element
	public String delimiter;	
	
	@AnyElement
	public List<Object> any;	
	
    
}