// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Information that describes an item's condition.
 * 
 */
public class Condition implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public Integer conditionId;	
	
	@Element
	public String conditionDisplayName;	
	
	@Element
	public String delimiter;	
	
	@AnyElement
	public List<Object> any;	
	
    
}