// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Response container for the findItemsByProduct call.
 * 
 */
@RootElement(name = "findItemsByProductResponse", namespace = "http://www.ebay.com/marketplace/search/v1/services")
public class FindItemsByProductResponse extends BaseFindingServiceResponse implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public AspectHistogramContainer aspectHistogramContainer;	
	
	@Element
	public ConditionHistogramContainer conditionHistogramContainer;	
	
    
}