// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the specifications for limiting the number of items returned by a find request. Use <b class="con">itemFilter</b> to specify name/value pairs. You can include multiple item filters in a single request.
 * 
 */
public class ItemFilter implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public String paramName;	
	
	@Element
	@Order(value=1)
	public String paramValue;	
	
	@Element
	@Order(value=2)
	public ItemFilterType name;	
	
	@Element
	@Order(value=3)
	public List<String> value;	
	
	@Element
	@Order(value=4)
	public String delimiter;	
	
	@AnyElement
	@Order(value=5)
	public List<Object> any;	
	
    
}