// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Shows the pagination data for the item search. Child elements include the
 * page number returned, the maximum entries returned per page, the total number
 * of pages that can be returned, and the total number of items that match the
 * search criteria.
 * 
 */
public class PaginationOutput implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public Integer pageNumber;	
	
	@Element
	public Integer entriesPerPage;	
	
	@Element
	public Integer totalPages;	
	
	@Element
	public Integer totalEntries;	
	
	@Element
	public String delimiter;	
	
	@AnyElement
	public List<Object> any;	
	
    
}