// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the returned item listings, if any. The data for each listing is
 * returned in individual item containers.
 * 
 */
public class SearchResult implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public List<SearchItem> item;	
	
	@Element
	public String delimiter;	
	
	@AnyElement
	public List<Object> any;	
	
	@Attribute  
	public int count;	
	
    
}