// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Container for the data of a single item that matches the search criteria. Finding API calls return an object of this type, filled with the item's data.
 * 
 */
public class SearchItem implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public String itemId;	
	
	@Element
	public String title;	
	
	@Element
	public String globalId;	
	
	@Element
	public String subtitle;	
	
	@Element
	public Category primaryCategory;	
	
	@Element
	public Category secondaryCategory;	
	
	@Element
	public String galleryURL;	
	
	@Element
	public GalleryInfoContainer galleryInfoContainer;	
	
	@Element
	public String viewItemURL;	
	
	@Element
	public String charityId;	
	
	@Element
	public ProductId productId;	
	
	@Element
	public List<String> paymentMethod;	
	
	@Element
	public Boolean autoPay;	
	
	@Element
	public String postalCode;	
	
	@Element
	public String location;	
	
	@Element
	public String country;	
	
	@Element
	public Storefront storeInfo;	
	
	@Element
	public SellerInfo sellerInfo;	
	
	@Element
	public ShippingInfo shippingInfo;	
	
	@Element
	public SellingStatus sellingStatus;	
	
	@Element
	public ListingInfo listingInfo;	
	
	@Element
	public Boolean returnsAccepted;	
	
	@Element
	public List<String> galleryPlusPictureURL;	
	
	@Element
	public String compatibility;	
	
	@Element
	public Distance distance;	
	
	@Element
	public Condition condition;	
	
	@Element
	public Boolean isMultiVariationListing;	
	
	@Element
	public DiscountPriceInfo discountPriceInfo;	
	
	@Element
	public String pictureURLSuperSize;	
	
	@Element
	public String pictureURLLarge;	
	
	@Element
	public UnitPriceInfo unitPrice;	
	
	@Element
	public List<ItemAttribute> attribute;	
	
	@Element
	public Boolean topRatedListing;	
	
	@Element
	public String delimiter;	
	
	@AnyElement
	public List<Object> any;	
	
    
}