// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.itemattributes;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class Creator implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	public String value;	
	
	@Attribute(name = "Role")
	public String role;	
	
    
}