// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.itemattributes;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

public class EANList implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "EANListElement")
	@Order(value=0)
	public List<String> eanListElement;	
	
    
}