// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.collections;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionItem;
import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionParent;
import java.util.List;
import com.amazon.webservices.awsecommerceservice._2011_08_01.collections.collection.CollectionSummary;

public class Collection implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CollectionSummary")
	public CollectionSummary collectionSummary;	
	
	@Element(name = "CollectionParent")
	public CollectionParent collectionParent;	
	
	@Element(name = "CollectionItem")
	public List<CollectionItem> collectionItem;	
	
    
}