// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api.client;


import com.leansoft.nano.ws.XMLServiceCallback;
import com.leansoft.nano.ws.NanoXMLClient;
import com.ebay.trading.api.SetSellingManagerFeedbackOptionsRequestType;
import com.ebay.trading.api.GetContextualKeywordsResponseType;
import com.ebay.trading.api.DisableUnpaidItemAssistanceResponseType;
import com.ebay.trading.api.GetApiAccessRulesResponseType;
import com.ebay.trading.api.AddSellingManagerInventoryFolderRequestType;
import com.ebay.trading.api.GeteBayDetailsRequestType;
import com.ebay.trading.api.UploadSiteHostedPicturesResponseType;
import com.ebay.trading.api.GetSellingManagerTemplatesResponseType;
import com.ebay.trading.api.SaveItemToSellingManagerTemplateRequestType;
import com.ebay.trading.api.GetPromotionRulesResponseType;
import com.ebay.trading.api.ValidateChallengeInputRequestType;
import com.ebay.trading.api.ReviseItemResponseType;
import com.ebay.trading.api.GetMemberMessagesRequestType;
import com.ebay.trading.api.GetClientAlertsAuthTokenRequestType;
import com.ebay.trading.api.SetUserPreferencesResponseType;
import com.ebay.trading.api.SetUserNotesResponseType;
import com.ebay.trading.api.GeteBayOfficialTimeResponseType;
import com.ebay.trading.api.RelistItemRequestType;
import com.ebay.trading.api.GetVeROReportStatusResponseType;
import com.ebay.trading.api.GetCategorySpecificsRequestType;
import com.ebay.trading.api.GetMyeBaySellingResponseType;
import com.ebay.trading.api.GetSellingManagerEmailLogRequestType;
import com.ebay.trading.api.AddItemFromSellingManagerTemplateRequestType;
import com.ebay.trading.api.ConfirmIdentityRequestType;
import com.ebay.trading.api.ReviseSellingManagerProductRequestType;
import com.ebay.trading.api.GetCharitiesResponseType;
import com.ebay.trading.api.GetSellingManagerSaleRecordRequestType;
import com.ebay.trading.api.ReviseItemRequestType;
import com.ebay.trading.api.GeteBayOfficialTimeRequestType;
import com.ebay.trading.api.GetMyeBayRemindersResponseType;
import com.ebay.trading.api.RespondToWantItNowPostResponseType;
import com.ebay.trading.api.AddToItemDescriptionResponseType;
import com.ebay.trading.api.ReviseMyMessagesFoldersResponseType;
import com.ebay.trading.api.GetVeROReasonCodeDetailsRequestType;
import com.ebay.trading.api.GetDescriptionTemplatesResponseType;
import com.ebay.trading.api.GetItemTransactionsRequestType;
import com.ebay.trading.api.VerifyAddItemResponseType;
import com.ebay.trading.api.GetSellerPaymentsRequestType;
import com.ebay.trading.api.GetAccountResponseType;
import com.ebay.trading.api.SetSellingManagerTemplateAutomationRuleResponseType;
import com.ebay.trading.api.GetUserDisputesResponseType;
import com.ebay.trading.api.GetTokenStatusResponseType;
import com.ebay.trading.api.GetStoreCategoryUpdateStatusRequestType;
import com.ebay.trading.api.VerifyRelistItemRequestType;
import com.ebay.trading.api.ReviseFixedPriceItemRequestType;
import com.ebay.trading.api.AddSellingManagerTemplateRequestType;
import com.ebay.trading.api.SetStoreCategoriesResponseType;
import com.ebay.trading.api.DeleteSellingManagerProductResponseType;
import com.ebay.trading.api.GetProductFamilyMembersRequestType;
import com.ebay.trading.api.PlaceOfferRequestType;
import com.ebay.trading.api.GetBidderListResponseType;
import com.ebay.trading.api.AddItemsResponseType;
import com.ebay.trading.api.GetMyMessagesResponseType;
import com.ebay.trading.api.GetVeROReasonCodeDetailsResponseType;
import com.ebay.trading.api.AddMemberMessageAAQToPartnerResponseType;
import com.ebay.trading.api.RespondToWantItNowPostRequestType;
import com.ebay.trading.api.EndItemResponseType;
import com.ebay.trading.api.ConfirmIdentityResponseType;
import com.ebay.trading.api.VeROReportItemsRequestType;
import com.ebay.trading.api.AddFixedPriceItemResponseType;
import com.ebay.trading.api.AddFixedPriceItemRequestType;
import com.ebay.trading.api.SetUserPreferencesRequestType;
import com.ebay.trading.api.SetMessagePreferencesResponseType;
import com.ebay.trading.api.SellerReverseDisputeResponseType;
import com.ebay.trading.api.GetCategory2CSRequestType;
import com.ebay.trading.api.GeteBayDetailsResponseType;
import com.ebay.trading.api.GetChallengeTokenRequestType;
import com.ebay.trading.api.GetSellerDashboardResponseType;
import com.ebay.trading.api.AddItemResponseType;
import com.ebay.trading.api.DeleteMyMessagesRequestType;
import com.ebay.trading.api.DeleteSellingManagerProductRequestType;
import com.ebay.trading.api.AddMemberMessageRTQResponseType;
import com.ebay.trading.api.CompleteSaleRequestType;
import com.ebay.trading.api.GetCategoryMappingsRequestType;
import com.ebay.trading.api.DeleteSellingManagerTemplateAutomationRuleResponseType;
import com.ebay.trading.api.GetNotificationPreferencesRequestType;
import com.ebay.trading.api.GetSellingManagerItemAutomationRuleResponseType;
import com.ebay.trading.api.GetProductSearchPageRequestType;
import com.ebay.trading.api.GetCrossPromotionsRequestType;
import com.ebay.trading.api.RelistFixedPriceItemResponseType;
import com.ebay.trading.api.GetPromotionalSaleDetailsResponseType;
import com.ebay.trading.api.GetStoreOptionsRequestType;
import com.ebay.trading.api.AddDisputeResponseResponseType;
import com.ebay.trading.api.GetSellingManagerAlertsRequestType;
import com.ebay.trading.api.GetOrdersRequestType;
import com.ebay.trading.api.AddDisputeResponseType;
import com.ebay.trading.api.GetUserRequestType;
import com.ebay.trading.api.GetBidderListRequestType;
import com.ebay.trading.api.GetUserPreferencesResponseType;
import com.ebay.trading.api.DeleteSellingManagerTemplateAutomationRuleRequestType;
import com.ebay.trading.api.GetSellingManagerItemAutomationRuleRequestType;
import com.ebay.trading.api.AddOrderResponseType;
import com.ebay.trading.api.GetSellingManagerInventoryResponseType;
import com.ebay.trading.api.GetAttributesCSResponseType;
import com.ebay.trading.api.GetSellerEventsResponseType;
import com.ebay.trading.api.GetSellingManagerEmailLogResponseType;
import com.ebay.trading.api.GetSessionIDResponseType;
import com.ebay.trading.api.GetSellingManagerTemplatesRequestType;
import com.ebay.trading.api.AddItemsRequestType;
import com.ebay.trading.api.GetStoreOptionsResponseType;
import com.ebay.trading.api.GetSellingManagerTemplateAutomationRuleResponseType;
import com.ebay.trading.api.ReviseFixedPriceItemResponseType;
import com.ebay.trading.api.VerifyAddSecondChanceItemRequestType;
import com.ebay.trading.api.GetCategoryFeaturesRequestType;
import com.ebay.trading.api.GetSellingManagerAlertsResponseType;
import com.ebay.trading.api.AddSellingManagerProductRequestType;
import com.ebay.trading.api.GetAttributesXSLRequestType;
import com.ebay.trading.api.GetItemsAwaitingFeedbackResponseType;
import com.ebay.trading.api.RemoveFromWatchListRequestType;
import com.ebay.trading.api.RespondToFeedbackResponseType;
import com.ebay.trading.api.GetProductFinderXSLRequestType;
import com.ebay.trading.api.GetMemberMessagesResponseType;
import com.ebay.trading.api.GetProductFinderXSLResponseType;
import com.ebay.trading.api.ExtendSiteHostedPicturesRequestType;
import com.ebay.trading.api.GetOrderTransactionsResponseType;
import com.ebay.trading.api.RelistItemResponseType;
import com.ebay.trading.api.SetPromotionalSaleListingsResponseType;
import com.ebay.trading.api.SetPromotionalSaleResponseType;
import com.ebay.trading.api.AddMemberMessagesAAQToBidderResponseType;
import com.ebay.trading.api.IssueRefundRequestType;
import com.ebay.trading.api.GetAttributesCSRequestType;
import com.ebay.trading.api.ReviseSellingManagerInventoryFolderResponseType;
import com.ebay.trading.api.AddSellingManagerProductResponseType;
import com.ebay.trading.api.GetSellerPaymentsResponseType;
import com.ebay.trading.api.ReviseMyMessagesFoldersRequestType;
import com.ebay.trading.api.GetStoreCustomPageResponseType;
import com.ebay.trading.api.GetOrderTransactionsRequestType;
import com.ebay.trading.api.FetchTokenResponseType;
import com.ebay.trading.api.AddMemberMessagesAAQToBidderRequestType;
import com.ebay.trading.api.GetMyeBayRemindersRequestType;
import com.ebay.trading.api.RespondToFeedbackRequestType;
import com.ebay.trading.api.FetchTokenRequestType;
import com.ebay.trading.api.AddSecondChanceItemResponseType;
import com.ebay.trading.api.SaveItemToSellingManagerTemplateResponseType;
import com.ebay.trading.api.RelistFixedPriceItemRequestType;
import com.ebay.trading.api.AddMemberMessageAAQToPartnerRequestType;
import com.ebay.trading.api.GetItemShippingResponseType;
import com.ebay.trading.api.CompleteSaleResponseType;
import com.ebay.trading.api.GetCrossPromotionsResponseType;
import com.ebay.trading.api.RemoveFromWatchListResponseType;
import com.ebay.trading.api.DeleteSellingManagerTemplateResponseType;
import com.ebay.trading.api.SetTaxTableRequestType;
import com.ebay.trading.api.ValidateTestUserRegistrationResponseType;
import com.ebay.trading.api.ReviseMyMessagesRequestType;
import com.ebay.trading.api.SendInvoiceRequestType;
import com.ebay.trading.api.GetMyeBaySellingRequestType;
import com.ebay.trading.api.GetProductSellingPagesResponseType;
import com.ebay.trading.api.GetProductFinderRequestType;
import com.ebay.trading.api.VerifyAddFixedPriceItemResponseType;
import com.ebay.trading.api.GetCategory2CSResponseType;
import com.ebay.trading.api.GetUserContactDetailsRequestType;
import com.ebay.trading.api.AddMemberMessageRTQRequestType;
import com.ebay.trading.api.GetMessagePreferencesRequestType;
import com.ebay.trading.api.SellerReverseDisputeRequestType;
import com.ebay.trading.api.GetUserResponseType;
import com.ebay.trading.api.GetWantItNowPostRequestType;
import com.ebay.trading.api.GetItemRecommendationsRequestType;
import com.ebay.trading.api.GetSellingManagerSoldListingsResponseType;
import com.ebay.trading.api.SetStoreRequestType;
import com.ebay.trading.api.SetPromotionalSaleListingsRequestType;
import com.ebay.trading.api.DeleteMyMessagesResponseType;
import com.ebay.trading.api.GetPromotionRulesRequestType;
import com.ebay.trading.api.GetSellingManagerInventoryFolderResponseType;
import com.ebay.trading.api.AddDisputeRequestType;
import com.ebay.trading.api.AddToWatchListRequestType;
import com.ebay.trading.api.GetItemTransactionsResponseType;
import com.ebay.trading.api.GetSellerDashboardRequestType;
import com.ebay.trading.api.ReviseInventoryStatusResponseType;
import com.ebay.trading.api.UploadSiteHostedPicturesRequestType;
import com.ebay.trading.api.GetTaxTableRequestType;
import com.ebay.trading.api.GetItemRecommendationsResponseType;
import com.ebay.trading.api.ReviseInventoryStatusRequestType;
import com.ebay.trading.api.GetCategoryMappingsResponseType;
import com.ebay.trading.api.PlaceOfferResponseType;
import com.ebay.trading.api.ReviseSellingManagerTemplateRequestType;
import com.ebay.trading.api.GetWantItNowSearchResultsResponseType;
import com.ebay.trading.api.GetNotificationPreferencesResponseType;
import com.ebay.trading.api.GetPromotionalSaleDetailsRequestType;
import com.ebay.trading.api.GetWantItNowSearchResultsRequestType;
import com.ebay.trading.api.GetBestOffersResponseType;
import com.ebay.trading.api.GetStorePreferencesResponseType;
import com.ebay.trading.api.AddTransactionConfirmationItemRequestType;
import com.ebay.trading.api.VerifyAddItemRequestType;
import com.ebay.trading.api.SetSellingManagerFeedbackOptionsResponseType;
import com.ebay.trading.api.MoveSellingManagerInventoryFolderRequestType;
import com.ebay.trading.api.EndFixedPriceItemResponseType;
import com.ebay.trading.api.EndFixedPriceItemRequestType;
import com.ebay.trading.api.ReviseSellingManagerSaleRecordRequestType;
import com.ebay.trading.api.GetTokenStatusRequestType;
import com.ebay.trading.api.GetDescriptionTemplatesRequestType;
import com.ebay.trading.api.AddToWatchListResponseType;
import com.ebay.trading.api.GetSellingManagerSaleRecordResponseType;
import com.ebay.trading.api.GetSellingManagerInventoryFolderRequestType;
import com.ebay.trading.api.SetStoreCategoriesRequestType;
import com.ebay.trading.api.GetStorePreferencesRequestType;
import com.ebay.trading.api.SetSellingManagerItemAutomationRuleResponseType;
import com.ebay.trading.api.DeleteSellingManagerInventoryFolderResponseType;
import com.ebay.trading.api.AddOrderRequestType;
import com.ebay.trading.api.SetStoreCustomPageRequestType;
import com.ebay.trading.api.GetContextualKeywordsRequestType;
import com.ebay.trading.api.GetDisputeResponseType;
import com.ebay.trading.api.SetNotificationPreferencesRequestType;
import com.ebay.trading.api.GetItemShippingRequestType;
import com.ebay.trading.api.GetSuggestedCategoriesResponseType;
import com.ebay.trading.api.GetCharitiesRequestType;
import com.ebay.trading.api.SetStorePreferencesRequestType;
import com.ebay.trading.api.EndItemsResponseType;
import com.ebay.trading.api.AddSecondChanceItemRequestType;
import com.ebay.trading.api.DeleteSellingManagerTemplateRequestType;
import com.ebay.trading.api.AddSellingManagerTemplateResponseType;
import com.ebay.trading.api.GetOrdersResponseType;
import com.ebay.trading.api.GetMyeBayBuyingRequestType;
import com.ebay.trading.api.RespondToBestOfferRequestType;
import com.ebay.trading.api.DeleteSellingManagerItemAutomationRuleResponseType;
import com.ebay.trading.api.GetUserDisputesRequestType;
import com.ebay.trading.api.AddItemFromSellingManagerTemplateResponseType;
import com.ebay.trading.api.SendInvoiceResponseType;
import com.ebay.trading.api.GetUserPreferencesRequestType;
import com.ebay.trading.api.DeleteSellingManagerItemAutomationRuleRequestType;
import com.ebay.trading.api.SetStoreResponseType;
import com.ebay.trading.api.ReviseSellingManagerTemplateResponseType;
import com.ebay.trading.api.GetApiAccessRulesRequestType;
import com.ebay.trading.api.GetMyMessagesRequestType;
import com.ebay.trading.api.GetChallengeTokenResponseType;
import com.ebay.trading.api.LeaveFeedbackRequestType;
import com.ebay.trading.api.SetMessagePreferencesRequestType;
import com.ebay.trading.api.SetSellingManagerItemAutomationRuleRequestType;
import com.ebay.trading.api.GetCategoriesRequestType;
import com.ebay.trading.api.SetNotificationPreferencesResponseType;
import com.ebay.trading.api.GetAllBiddersRequestType;
import com.ebay.trading.api.RevokeTokenResponseType;
import com.ebay.trading.api.GetFeedbackRequestType;
import com.ebay.trading.api.ReviseSellingManagerInventoryFolderRequestType;
import com.ebay.trading.api.ReviseCheckoutStatusResponseType;
import com.ebay.trading.api.GetSellerListRequestType;
import com.ebay.trading.api.GetStoreRequestType;
import com.ebay.trading.api.GetMessagePreferencesResponseType;
import com.ebay.trading.api.ReviseSellingManagerSaleRecordResponseType;
import com.ebay.trading.api.GetProductFamilyMembersResponseType;
import com.ebay.trading.api.GetSellerTransactionsResponseType;
import com.ebay.trading.api.GetClientAlertsAuthTokenResponseType;
import com.ebay.trading.api.GetCategorySpecificsResponseType;
import com.ebay.trading.api.GetShippingDiscountProfilesRequestType;
import com.ebay.trading.api.SetStoreCustomPageResponseType;
import com.ebay.trading.api.SetShippingDiscountProfilesRequestType;
import com.ebay.trading.api.GetBestOffersRequestType;
import com.ebay.trading.api.SetUserNotesRequestType;
import com.ebay.trading.api.GetProductFinderResponseType;
import com.ebay.trading.api.ReviseCheckoutStatusRequestType;
import com.ebay.trading.api.GetDisputeRequestType;
import com.ebay.trading.api.GetSellerEventsRequestType;
import com.ebay.trading.api.ReviseSellingManagerProductResponseType;
import com.ebay.trading.api.GetAccountRequestType;
import com.ebay.trading.api.DisableUnpaidItemAssistanceRequestType;
import com.ebay.trading.api.AddToItemDescriptionRequestType;
import com.ebay.trading.api.GetSellingManagerSoldListingsRequestType;
import com.ebay.trading.api.GetShippingDiscountProfilesResponseType;
import com.ebay.trading.api.GetVeROReportStatusRequestType;
import com.ebay.trading.api.DeleteSellingManagerInventoryFolderRequestType;
import com.ebay.trading.api.GetProductSearchPageResponseType;
import com.ebay.trading.api.SetShippingDiscountProfilesResponseType;
import com.ebay.trading.api.LeaveFeedbackResponseType;
import com.ebay.trading.api.GetCategoryFeaturesResponseType;
import com.ebay.trading.api.GetAttributesXSLResponseType;
import com.ebay.trading.api.ExtendSiteHostedPicturesResponseType;
import com.ebay.trading.api.GetItemRequestType;
import com.ebay.trading.api.ReviseMyMessagesResponseType;
import com.ebay.trading.api.IssueRefundResponseType;
import com.ebay.trading.api.GetNotificationsUsageRequestType;
import com.ebay.trading.api.RespondToBestOfferResponseType;
import com.ebay.trading.api.VeROReportItemsResponseType;
import com.ebay.trading.api.GetStoreCustomPageRequestType;
import com.ebay.trading.api.GetAllBiddersResponseType;
import com.ebay.trading.api.GetSellingManagerInventoryRequestType;
import com.ebay.trading.api.EndItemRequestType;
import com.ebay.trading.api.GetStoreCategoryUpdateStatusResponseType;
import com.ebay.trading.api.GetTaxTableResponseType;
import com.ebay.trading.api.GetProductSellingPagesRequestType;
import com.ebay.trading.api.GetSellingManagerTemplateAutomationRuleRequestType;
import com.ebay.trading.api.GetSellerListResponseType;
import com.ebay.trading.api.GetAdFormatLeadsRequestType;
import com.ebay.trading.api.SetStorePreferencesResponseType;
import com.ebay.trading.api.GetStoreResponseType;
import com.ebay.trading.api.VerifyAddFixedPriceItemRequestType;
import com.ebay.trading.api.ValidateTestUserRegistrationRequestType;
import com.ebay.trading.api.VerifyRelistItemResponseType;
import com.ebay.trading.api.RevokeTokenRequestType;
import com.ebay.trading.api.GetItemResponseType;
import com.ebay.trading.api.GetMyeBayBuyingResponseType;
import com.ebay.trading.api.GetUserContactDetailsResponseType;
import com.ebay.trading.api.AddItemRequestType;
import com.ebay.trading.api.GetProductSearchResultsResponseType;
import com.ebay.trading.api.GetAdFormatLeadsResponseType;
import com.ebay.trading.api.SetSellingManagerTemplateAutomationRuleRequestType;
import com.ebay.trading.api.EndItemsRequestType;
import com.ebay.trading.api.SetPromotionalSaleRequestType;
import com.ebay.trading.api.GetFeedbackResponseType;
import com.ebay.trading.api.AddSellingManagerInventoryFolderResponseType;
import com.ebay.trading.api.GetItemsAwaitingFeedbackRequestType;
import com.ebay.trading.api.ValidateChallengeInputResponseType;
import com.ebay.trading.api.GetSuggestedCategoriesRequestType;
import com.ebay.trading.api.GetNotificationsUsageResponseType;
import com.ebay.trading.api.AddTransactionConfirmationItemResponseType;
import com.ebay.trading.api.GetCategoriesResponseType;
import com.ebay.trading.api.GetWantItNowPostResponseType;
import com.ebay.trading.api.MoveSellingManagerInventoryFolderResponseType;
import com.ebay.trading.api.AddDisputeResponseRequestType;
import com.ebay.trading.api.GetSellerTransactionsRequestType;
import com.ebay.trading.api.SetTaxTableResponseType;
import com.ebay.trading.api.GetSessionIDRequestType;
import com.ebay.trading.api.GetProductSearchResultsRequestType;
import com.ebay.trading.api.VerifyAddSecondChanceItemResponseType;


/**
 This class is the XML client to the EBayAPIInterface Web Service.
*/ 
public class EBayAPIInterface_XMLClient extends NanoXMLClient {


    /**
     public method
    */
    public void addDispute(AddDisputeRequestType requestObject, XMLServiceCallback<AddDisputeResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddDisputeResponseType.class);
    }

    /**
     public method
    */
    public void addDisputeResponse(AddDisputeResponseRequestType requestObject, XMLServiceCallback<AddDisputeResponseResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddDisputeResponseResponseType.class);
    }

    /**
     public method
    */
    public void addFixedPriceItem(AddFixedPriceItemRequestType requestObject, XMLServiceCallback<AddFixedPriceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddFixedPriceItemResponseType.class);
    }

    /**
     public method
    */
    public void addItem(AddItemRequestType requestObject, XMLServiceCallback<AddItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddItemResponseType.class);
    }

    /**
     public method
    */
    public void addItemFromSellingManagerTemplate(AddItemFromSellingManagerTemplateRequestType requestObject, XMLServiceCallback<AddItemFromSellingManagerTemplateResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddItemFromSellingManagerTemplateResponseType.class);
    }

    /**
     public method
    */
    public void addItems(AddItemsRequestType requestObject, XMLServiceCallback<AddItemsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddItemsResponseType.class);
    }

    /**
     public method
    */
    public void addMemberMessageAAQToPartner(AddMemberMessageAAQToPartnerRequestType requestObject, XMLServiceCallback<AddMemberMessageAAQToPartnerResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddMemberMessageAAQToPartnerResponseType.class);
    }

    /**
     public method
    */
    public void addMemberMessageRTQ(AddMemberMessageRTQRequestType requestObject, XMLServiceCallback<AddMemberMessageRTQResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddMemberMessageRTQResponseType.class);
    }

    /**
     public method
    */
    public void addMemberMessagesAAQToBidder(AddMemberMessagesAAQToBidderRequestType requestObject, XMLServiceCallback<AddMemberMessagesAAQToBidderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddMemberMessagesAAQToBidderResponseType.class);
    }

    /**
     public method
    */
    public void addOrder(AddOrderRequestType requestObject, XMLServiceCallback<AddOrderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddOrderResponseType.class);
    }

    /**
     public method
    */
    public void addSecondChanceItem(AddSecondChanceItemRequestType requestObject, XMLServiceCallback<AddSecondChanceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddSecondChanceItemResponseType.class);
    }

    /**
     public method
    */
    public void addSellingManagerInventoryFolder(AddSellingManagerInventoryFolderRequestType requestObject, XMLServiceCallback<AddSellingManagerInventoryFolderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddSellingManagerInventoryFolderResponseType.class);
    }

    /**
     public method
    */
    public void addSellingManagerProduct(AddSellingManagerProductRequestType requestObject, XMLServiceCallback<AddSellingManagerProductResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddSellingManagerProductResponseType.class);
    }

    /**
     public method
    */
    public void addSellingManagerTemplate(AddSellingManagerTemplateRequestType requestObject, XMLServiceCallback<AddSellingManagerTemplateResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddSellingManagerTemplateResponseType.class);
    }

    /**
     public method
    */
    public void addToItemDescription(AddToItemDescriptionRequestType requestObject, XMLServiceCallback<AddToItemDescriptionResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddToItemDescriptionResponseType.class);
    }

    /**
     public method
    */
    public void addToWatchList(AddToWatchListRequestType requestObject, XMLServiceCallback<AddToWatchListResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddToWatchListResponseType.class);
    }

    /**
     public method
    */
    public void addTransactionConfirmationItem(AddTransactionConfirmationItemRequestType requestObject, XMLServiceCallback<AddTransactionConfirmationItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, AddTransactionConfirmationItemResponseType.class);
    }

    /**
     public method
    */
    public void completeSale(CompleteSaleRequestType requestObject, XMLServiceCallback<CompleteSaleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CompleteSaleResponseType.class);
    }

    /**
     public method
    */
    public void confirmIdentity(ConfirmIdentityRequestType requestObject, XMLServiceCallback<ConfirmIdentityResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ConfirmIdentityResponseType.class);
    }

    /**
     public method
    */
    public void deleteMyMessages(DeleteMyMessagesRequestType requestObject, XMLServiceCallback<DeleteMyMessagesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteMyMessagesResponseType.class);
    }

    /**
     public method
    */
    public void deleteSellingManagerInventoryFolder(DeleteSellingManagerInventoryFolderRequestType requestObject, XMLServiceCallback<DeleteSellingManagerInventoryFolderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteSellingManagerInventoryFolderResponseType.class);
    }

    /**
     public method
    */
    public void deleteSellingManagerItemAutomationRule(DeleteSellingManagerItemAutomationRuleRequestType requestObject, XMLServiceCallback<DeleteSellingManagerItemAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteSellingManagerItemAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void deleteSellingManagerProduct(DeleteSellingManagerProductRequestType requestObject, XMLServiceCallback<DeleteSellingManagerProductResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteSellingManagerProductResponseType.class);
    }

    /**
     public method
    */
    public void deleteSellingManagerTemplate(DeleteSellingManagerTemplateRequestType requestObject, XMLServiceCallback<DeleteSellingManagerTemplateResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteSellingManagerTemplateResponseType.class);
    }

    /**
     public method
    */
    public void deleteSellingManagerTemplateAutomationRule(DeleteSellingManagerTemplateAutomationRuleRequestType requestObject, XMLServiceCallback<DeleteSellingManagerTemplateAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DeleteSellingManagerTemplateAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void disableUnpaidItemAssistance(DisableUnpaidItemAssistanceRequestType requestObject, XMLServiceCallback<DisableUnpaidItemAssistanceResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, DisableUnpaidItemAssistanceResponseType.class);
    }

    /**
     public method
    */
    public void endFixedPriceItem(EndFixedPriceItemRequestType requestObject, XMLServiceCallback<EndFixedPriceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, EndFixedPriceItemResponseType.class);
    }

    /**
     public method
    */
    public void endItem(EndItemRequestType requestObject, XMLServiceCallback<EndItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, EndItemResponseType.class);
    }

    /**
     public method
    */
    public void endItems(EndItemsRequestType requestObject, XMLServiceCallback<EndItemsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, EndItemsResponseType.class);
    }

    /**
     public method
    */
    public void extendSiteHostedPictures(ExtendSiteHostedPicturesRequestType requestObject, XMLServiceCallback<ExtendSiteHostedPicturesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ExtendSiteHostedPicturesResponseType.class);
    }

    /**
     public method
    */
    public void fetchToken(FetchTokenRequestType requestObject, XMLServiceCallback<FetchTokenResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FetchTokenResponseType.class);
    }

    /**
     public method
    */
    public void getAccount(GetAccountRequestType requestObject, XMLServiceCallback<GetAccountResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetAccountResponseType.class);
    }

    /**
     public method
    */
    public void getAdFormatLeads(GetAdFormatLeadsRequestType requestObject, XMLServiceCallback<GetAdFormatLeadsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetAdFormatLeadsResponseType.class);
    }

    /**
     public method
    */
    public void getAllBidders(GetAllBiddersRequestType requestObject, XMLServiceCallback<GetAllBiddersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetAllBiddersResponseType.class);
    }

    /**
     public method
    */
    public void getApiAccessRules(GetApiAccessRulesRequestType requestObject, XMLServiceCallback<GetApiAccessRulesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetApiAccessRulesResponseType.class);
    }

    /**
     public method
    */
    public void getAttributesCS(GetAttributesCSRequestType requestObject, XMLServiceCallback<GetAttributesCSResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetAttributesCSResponseType.class);
    }

    /**
     public method
    */
    public void getAttributesXSL(GetAttributesXSLRequestType requestObject, XMLServiceCallback<GetAttributesXSLResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetAttributesXSLResponseType.class);
    }

    /**
     public method
    */
    public void getBestOffers(GetBestOffersRequestType requestObject, XMLServiceCallback<GetBestOffersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetBestOffersResponseType.class);
    }

    /**
     public method
    */
    public void getBidderList(GetBidderListRequestType requestObject, XMLServiceCallback<GetBidderListResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetBidderListResponseType.class);
    }

    /**
     public method
    */
    public void getCategories(GetCategoriesRequestType requestObject, XMLServiceCallback<GetCategoriesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCategoriesResponseType.class);
    }

    /**
     public method
    */
    public void getCategory2CS(GetCategory2CSRequestType requestObject, XMLServiceCallback<GetCategory2CSResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCategory2CSResponseType.class);
    }

    /**
     public method
    */
    public void getCategoryFeatures(GetCategoryFeaturesRequestType requestObject, XMLServiceCallback<GetCategoryFeaturesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCategoryFeaturesResponseType.class);
    }

    /**
     public method
    */
    public void getCategoryMappings(GetCategoryMappingsRequestType requestObject, XMLServiceCallback<GetCategoryMappingsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCategoryMappingsResponseType.class);
    }

    /**
     public method
    */
    public void getCategorySpecifics(GetCategorySpecificsRequestType requestObject, XMLServiceCallback<GetCategorySpecificsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCategorySpecificsResponseType.class);
    }

    /**
     public method
    */
    public void getChallengeToken(GetChallengeTokenRequestType requestObject, XMLServiceCallback<GetChallengeTokenResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetChallengeTokenResponseType.class);
    }

    /**
     public method
    */
    public void getCharities(GetCharitiesRequestType requestObject, XMLServiceCallback<GetCharitiesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCharitiesResponseType.class);
    }

    /**
     public method
    */
    public void getClientAlertsAuthToken(GetClientAlertsAuthTokenRequestType requestObject, XMLServiceCallback<GetClientAlertsAuthTokenResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetClientAlertsAuthTokenResponseType.class);
    }

    /**
     public method
    */
    public void getContextualKeywords(GetContextualKeywordsRequestType requestObject, XMLServiceCallback<GetContextualKeywordsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetContextualKeywordsResponseType.class);
    }

    /**
     public method
    */
    public void getCrossPromotions(GetCrossPromotionsRequestType requestObject, XMLServiceCallback<GetCrossPromotionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetCrossPromotionsResponseType.class);
    }

    /**
     public method
    */
    public void getDescriptionTemplates(GetDescriptionTemplatesRequestType requestObject, XMLServiceCallback<GetDescriptionTemplatesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetDescriptionTemplatesResponseType.class);
    }

    /**
     public method
    */
    public void getDispute(GetDisputeRequestType requestObject, XMLServiceCallback<GetDisputeResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetDisputeResponseType.class);
    }

    /**
     public method
    */
    public void getFeedback(GetFeedbackRequestType requestObject, XMLServiceCallback<GetFeedbackResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetFeedbackResponseType.class);
    }

    /**
     public method
    */
    public void getItem(GetItemRequestType requestObject, XMLServiceCallback<GetItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetItemResponseType.class);
    }

    /**
     public method
    */
    public void getItemRecommendations(GetItemRecommendationsRequestType requestObject, XMLServiceCallback<GetItemRecommendationsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetItemRecommendationsResponseType.class);
    }

    /**
     public method
    */
    public void getItemShipping(GetItemShippingRequestType requestObject, XMLServiceCallback<GetItemShippingResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetItemShippingResponseType.class);
    }

    /**
     public method
    */
    public void getItemTransactions(GetItemTransactionsRequestType requestObject, XMLServiceCallback<GetItemTransactionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetItemTransactionsResponseType.class);
    }

    /**
     public method
    */
    public void getItemsAwaitingFeedback(GetItemsAwaitingFeedbackRequestType requestObject, XMLServiceCallback<GetItemsAwaitingFeedbackResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetItemsAwaitingFeedbackResponseType.class);
    }

    /**
     public method
    */
    public void getMemberMessages(GetMemberMessagesRequestType requestObject, XMLServiceCallback<GetMemberMessagesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMemberMessagesResponseType.class);
    }

    /**
     public method
    */
    public void getMessagePreferences(GetMessagePreferencesRequestType requestObject, XMLServiceCallback<GetMessagePreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMessagePreferencesResponseType.class);
    }

    /**
     public method
    */
    public void getMyMessages(GetMyMessagesRequestType requestObject, XMLServiceCallback<GetMyMessagesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMyMessagesResponseType.class);
    }

    /**
     public method
    */
    public void getMyeBayBuying(GetMyeBayBuyingRequestType requestObject, XMLServiceCallback<GetMyeBayBuyingResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMyeBayBuyingResponseType.class);
    }

    /**
     public method
    */
    public void getMyeBayReminders(GetMyeBayRemindersRequestType requestObject, XMLServiceCallback<GetMyeBayRemindersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMyeBayRemindersResponseType.class);
    }

    /**
     public method
    */
    public void getMyeBaySelling(GetMyeBaySellingRequestType requestObject, XMLServiceCallback<GetMyeBaySellingResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetMyeBaySellingResponseType.class);
    }

    /**
     public method
    */
    public void getNotificationPreferences(GetNotificationPreferencesRequestType requestObject, XMLServiceCallback<GetNotificationPreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetNotificationPreferencesResponseType.class);
    }

    /**
     public method
    */
    public void getNotificationsUsage(GetNotificationsUsageRequestType requestObject, XMLServiceCallback<GetNotificationsUsageResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetNotificationsUsageResponseType.class);
    }

    /**
     public method
    */
    public void getOrderTransactions(GetOrderTransactionsRequestType requestObject, XMLServiceCallback<GetOrderTransactionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetOrderTransactionsResponseType.class);
    }

    /**
     public method
    */
    public void getOrders(GetOrdersRequestType requestObject, XMLServiceCallback<GetOrdersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetOrdersResponseType.class);
    }

    /**
     public method
    */
    public void getProductFamilyMembers(GetProductFamilyMembersRequestType requestObject, XMLServiceCallback<GetProductFamilyMembersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductFamilyMembersResponseType.class);
    }

    /**
     public method
    */
    public void getProductFinder(GetProductFinderRequestType requestObject, XMLServiceCallback<GetProductFinderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductFinderResponseType.class);
    }

    /**
     public method
    */
    public void getProductFinderXSL(GetProductFinderXSLRequestType requestObject, XMLServiceCallback<GetProductFinderXSLResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductFinderXSLResponseType.class);
    }

    /**
     public method
    */
    public void getProductSearchPage(GetProductSearchPageRequestType requestObject, XMLServiceCallback<GetProductSearchPageResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductSearchPageResponseType.class);
    }

    /**
     public method
    */
    public void getProductSearchResults(GetProductSearchResultsRequestType requestObject, XMLServiceCallback<GetProductSearchResultsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductSearchResultsResponseType.class);
    }

    /**
     public method
    */
    public void getProductSellingPages(GetProductSellingPagesRequestType requestObject, XMLServiceCallback<GetProductSellingPagesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetProductSellingPagesResponseType.class);
    }

    /**
     public method
    */
    public void getPromotionRules(GetPromotionRulesRequestType requestObject, XMLServiceCallback<GetPromotionRulesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetPromotionRulesResponseType.class);
    }

    /**
     public method
    */
    public void getPromotionalSaleDetails(GetPromotionalSaleDetailsRequestType requestObject, XMLServiceCallback<GetPromotionalSaleDetailsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetPromotionalSaleDetailsResponseType.class);
    }

    /**
     public method
    */
    public void getSellerDashboard(GetSellerDashboardRequestType requestObject, XMLServiceCallback<GetSellerDashboardResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellerDashboardResponseType.class);
    }

    /**
     public method
    */
    public void getSellerEvents(GetSellerEventsRequestType requestObject, XMLServiceCallback<GetSellerEventsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellerEventsResponseType.class);
    }

    /**
     public method
    */
    public void getSellerList(GetSellerListRequestType requestObject, XMLServiceCallback<GetSellerListResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellerListResponseType.class);
    }

    /**
     public method
    */
    public void getSellerPayments(GetSellerPaymentsRequestType requestObject, XMLServiceCallback<GetSellerPaymentsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellerPaymentsResponseType.class);
    }

    /**
     public method
    */
    public void getSellerTransactions(GetSellerTransactionsRequestType requestObject, XMLServiceCallback<GetSellerTransactionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellerTransactionsResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerAlerts(GetSellingManagerAlertsRequestType requestObject, XMLServiceCallback<GetSellingManagerAlertsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerAlertsResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerEmailLog(GetSellingManagerEmailLogRequestType requestObject, XMLServiceCallback<GetSellingManagerEmailLogResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerEmailLogResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerInventory(GetSellingManagerInventoryRequestType requestObject, XMLServiceCallback<GetSellingManagerInventoryResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerInventoryResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerInventoryFolder(GetSellingManagerInventoryFolderRequestType requestObject, XMLServiceCallback<GetSellingManagerInventoryFolderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerInventoryFolderResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerItemAutomationRule(GetSellingManagerItemAutomationRuleRequestType requestObject, XMLServiceCallback<GetSellingManagerItemAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerItemAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerSaleRecord(GetSellingManagerSaleRecordRequestType requestObject, XMLServiceCallback<GetSellingManagerSaleRecordResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerSaleRecordResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerSoldListings(GetSellingManagerSoldListingsRequestType requestObject, XMLServiceCallback<GetSellingManagerSoldListingsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerSoldListingsResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerTemplateAutomationRule(GetSellingManagerTemplateAutomationRuleRequestType requestObject, XMLServiceCallback<GetSellingManagerTemplateAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerTemplateAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void getSellingManagerTemplates(GetSellingManagerTemplatesRequestType requestObject, XMLServiceCallback<GetSellingManagerTemplatesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSellingManagerTemplatesResponseType.class);
    }

    /**
     public method
    */
    public void getSessionID(GetSessionIDRequestType requestObject, XMLServiceCallback<GetSessionIDResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSessionIDResponseType.class);
    }

    /**
     public method
    */
    public void getShippingDiscountProfiles(GetShippingDiscountProfilesRequestType requestObject, XMLServiceCallback<GetShippingDiscountProfilesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetShippingDiscountProfilesResponseType.class);
    }

    /**
     public method
    */
    public void getStore(GetStoreRequestType requestObject, XMLServiceCallback<GetStoreResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetStoreResponseType.class);
    }

    /**
     public method
    */
    public void getStoreCategoryUpdateStatus(GetStoreCategoryUpdateStatusRequestType requestObject, XMLServiceCallback<GetStoreCategoryUpdateStatusResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetStoreCategoryUpdateStatusResponseType.class);
    }

    /**
     public method
    */
    public void getStoreCustomPage(GetStoreCustomPageRequestType requestObject, XMLServiceCallback<GetStoreCustomPageResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetStoreCustomPageResponseType.class);
    }

    /**
     public method
    */
    public void getStoreOptions(GetStoreOptionsRequestType requestObject, XMLServiceCallback<GetStoreOptionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetStoreOptionsResponseType.class);
    }

    /**
     public method
    */
    public void getStorePreferences(GetStorePreferencesRequestType requestObject, XMLServiceCallback<GetStorePreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetStorePreferencesResponseType.class);
    }

    /**
     public method
    */
    public void getSuggestedCategories(GetSuggestedCategoriesRequestType requestObject, XMLServiceCallback<GetSuggestedCategoriesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSuggestedCategoriesResponseType.class);
    }

    /**
     public method
    */
    public void getTaxTable(GetTaxTableRequestType requestObject, XMLServiceCallback<GetTaxTableResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetTaxTableResponseType.class);
    }

    /**
     public method
    */
    public void getTokenStatus(GetTokenStatusRequestType requestObject, XMLServiceCallback<GetTokenStatusResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetTokenStatusResponseType.class);
    }

    /**
     public method
    */
    public void getUser(GetUserRequestType requestObject, XMLServiceCallback<GetUserResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetUserResponseType.class);
    }

    /**
     public method
    */
    public void getUserContactDetails(GetUserContactDetailsRequestType requestObject, XMLServiceCallback<GetUserContactDetailsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetUserContactDetailsResponseType.class);
    }

    /**
     public method
    */
    public void getUserDisputes(GetUserDisputesRequestType requestObject, XMLServiceCallback<GetUserDisputesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetUserDisputesResponseType.class);
    }

    /**
     public method
    */
    public void getUserPreferences(GetUserPreferencesRequestType requestObject, XMLServiceCallback<GetUserPreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetUserPreferencesResponseType.class);
    }

    /**
     public method
    */
    public void getVeROReasonCodeDetails(GetVeROReasonCodeDetailsRequestType requestObject, XMLServiceCallback<GetVeROReasonCodeDetailsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetVeROReasonCodeDetailsResponseType.class);
    }

    /**
     public method
    */
    public void getVeROReportStatus(GetVeROReportStatusRequestType requestObject, XMLServiceCallback<GetVeROReportStatusResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetVeROReportStatusResponseType.class);
    }

    /**
     public method
    */
    public void getWantItNowPost(GetWantItNowPostRequestType requestObject, XMLServiceCallback<GetWantItNowPostResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetWantItNowPostResponseType.class);
    }

    /**
     public method
    */
    public void getWantItNowSearchResults(GetWantItNowSearchResultsRequestType requestObject, XMLServiceCallback<GetWantItNowSearchResultsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetWantItNowSearchResultsResponseType.class);
    }

    /**
     public method
    */
    public void geteBayDetails(GeteBayDetailsRequestType requestObject, XMLServiceCallback<GeteBayDetailsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GeteBayDetailsResponseType.class);
    }

    /**
     public method
    */
    public void geteBayOfficialTime(GeteBayOfficialTimeRequestType requestObject, XMLServiceCallback<GeteBayOfficialTimeResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GeteBayOfficialTimeResponseType.class);
    }

    /**
     public method
    */
    public void issueRefund(IssueRefundRequestType requestObject, XMLServiceCallback<IssueRefundResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, IssueRefundResponseType.class);
    }

    /**
     public method
    */
    public void leaveFeedback(LeaveFeedbackRequestType requestObject, XMLServiceCallback<LeaveFeedbackResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, LeaveFeedbackResponseType.class);
    }

    /**
     public method
    */
    public void moveSellingManagerInventoryFolder(MoveSellingManagerInventoryFolderRequestType requestObject, XMLServiceCallback<MoveSellingManagerInventoryFolderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, MoveSellingManagerInventoryFolderResponseType.class);
    }

    /**
     public method
    */
    public void placeOffer(PlaceOfferRequestType requestObject, XMLServiceCallback<PlaceOfferResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, PlaceOfferResponseType.class);
    }

    /**
     public method
    */
    public void relistFixedPriceItem(RelistFixedPriceItemRequestType requestObject, XMLServiceCallback<RelistFixedPriceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RelistFixedPriceItemResponseType.class);
    }

    /**
     public method
    */
    public void relistItem(RelistItemRequestType requestObject, XMLServiceCallback<RelistItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RelistItemResponseType.class);
    }

    /**
     public method
    */
    public void removeFromWatchList(RemoveFromWatchListRequestType requestObject, XMLServiceCallback<RemoveFromWatchListResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RemoveFromWatchListResponseType.class);
    }

    /**
     public method
    */
    public void respondToBestOffer(RespondToBestOfferRequestType requestObject, XMLServiceCallback<RespondToBestOfferResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RespondToBestOfferResponseType.class);
    }

    /**
     public method
    */
    public void respondToFeedback(RespondToFeedbackRequestType requestObject, XMLServiceCallback<RespondToFeedbackResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RespondToFeedbackResponseType.class);
    }

    /**
     public method
    */
    public void respondToWantItNowPost(RespondToWantItNowPostRequestType requestObject, XMLServiceCallback<RespondToWantItNowPostResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RespondToWantItNowPostResponseType.class);
    }

    /**
     public method
    */
    public void reviseCheckoutStatus(ReviseCheckoutStatusRequestType requestObject, XMLServiceCallback<ReviseCheckoutStatusResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseCheckoutStatusResponseType.class);
    }

    /**
     public method
    */
    public void reviseFixedPriceItem(ReviseFixedPriceItemRequestType requestObject, XMLServiceCallback<ReviseFixedPriceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseFixedPriceItemResponseType.class);
    }

    /**
     public method
    */
    public void reviseInventoryStatus(ReviseInventoryStatusRequestType requestObject, XMLServiceCallback<ReviseInventoryStatusResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseInventoryStatusResponseType.class);
    }

    /**
     public method
    */
    public void reviseItem(ReviseItemRequestType requestObject, XMLServiceCallback<ReviseItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseItemResponseType.class);
    }

    /**
     public method
    */
    public void reviseMyMessages(ReviseMyMessagesRequestType requestObject, XMLServiceCallback<ReviseMyMessagesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseMyMessagesResponseType.class);
    }

    /**
     public method
    */
    public void reviseMyMessagesFolders(ReviseMyMessagesFoldersRequestType requestObject, XMLServiceCallback<ReviseMyMessagesFoldersResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseMyMessagesFoldersResponseType.class);
    }

    /**
     public method
    */
    public void reviseSellingManagerInventoryFolder(ReviseSellingManagerInventoryFolderRequestType requestObject, XMLServiceCallback<ReviseSellingManagerInventoryFolderResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseSellingManagerInventoryFolderResponseType.class);
    }

    /**
     public method
    */
    public void reviseSellingManagerProduct(ReviseSellingManagerProductRequestType requestObject, XMLServiceCallback<ReviseSellingManagerProductResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseSellingManagerProductResponseType.class);
    }

    /**
     public method
    */
    public void reviseSellingManagerSaleRecord(ReviseSellingManagerSaleRecordRequestType requestObject, XMLServiceCallback<ReviseSellingManagerSaleRecordResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseSellingManagerSaleRecordResponseType.class);
    }

    /**
     public method
    */
    public void reviseSellingManagerTemplate(ReviseSellingManagerTemplateRequestType requestObject, XMLServiceCallback<ReviseSellingManagerTemplateResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ReviseSellingManagerTemplateResponseType.class);
    }

    /**
     public method
    */
    public void revokeToken(RevokeTokenRequestType requestObject, XMLServiceCallback<RevokeTokenResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, RevokeTokenResponseType.class);
    }

    /**
     public method
    */
    public void saveItemToSellingManagerTemplate(SaveItemToSellingManagerTemplateRequestType requestObject, XMLServiceCallback<SaveItemToSellingManagerTemplateResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SaveItemToSellingManagerTemplateResponseType.class);
    }

    /**
     public method
    */
    public void sellerReverseDispute(SellerReverseDisputeRequestType requestObject, XMLServiceCallback<SellerReverseDisputeResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SellerReverseDisputeResponseType.class);
    }

    /**
     public method
    */
    public void sendInvoice(SendInvoiceRequestType requestObject, XMLServiceCallback<SendInvoiceResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SendInvoiceResponseType.class);
    }

    /**
     public method
    */
    public void setMessagePreferences(SetMessagePreferencesRequestType requestObject, XMLServiceCallback<SetMessagePreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetMessagePreferencesResponseType.class);
    }

    /**
     public method
    */
    public void setNotificationPreferences(SetNotificationPreferencesRequestType requestObject, XMLServiceCallback<SetNotificationPreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetNotificationPreferencesResponseType.class);
    }

    /**
     public method
    */
    public void setPromotionalSale(SetPromotionalSaleRequestType requestObject, XMLServiceCallback<SetPromotionalSaleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetPromotionalSaleResponseType.class);
    }

    /**
     public method
    */
    public void setPromotionalSaleListings(SetPromotionalSaleListingsRequestType requestObject, XMLServiceCallback<SetPromotionalSaleListingsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetPromotionalSaleListingsResponseType.class);
    }

    /**
     public method
    */
    public void setSellingManagerFeedbackOptions(SetSellingManagerFeedbackOptionsRequestType requestObject, XMLServiceCallback<SetSellingManagerFeedbackOptionsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetSellingManagerFeedbackOptionsResponseType.class);
    }

    /**
     public method
    */
    public void setSellingManagerItemAutomationRule(SetSellingManagerItemAutomationRuleRequestType requestObject, XMLServiceCallback<SetSellingManagerItemAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetSellingManagerItemAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void setSellingManagerTemplateAutomationRule(SetSellingManagerTemplateAutomationRuleRequestType requestObject, XMLServiceCallback<SetSellingManagerTemplateAutomationRuleResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetSellingManagerTemplateAutomationRuleResponseType.class);
    }

    /**
     public method
    */
    public void setShippingDiscountProfiles(SetShippingDiscountProfilesRequestType requestObject, XMLServiceCallback<SetShippingDiscountProfilesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetShippingDiscountProfilesResponseType.class);
    }

    /**
     public method
    */
    public void setStore(SetStoreRequestType requestObject, XMLServiceCallback<SetStoreResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetStoreResponseType.class);
    }

    /**
     public method
    */
    public void setStoreCategories(SetStoreCategoriesRequestType requestObject, XMLServiceCallback<SetStoreCategoriesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetStoreCategoriesResponseType.class);
    }

    /**
     public method
    */
    public void setStoreCustomPage(SetStoreCustomPageRequestType requestObject, XMLServiceCallback<SetStoreCustomPageResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetStoreCustomPageResponseType.class);
    }

    /**
     public method
    */
    public void setStorePreferences(SetStorePreferencesRequestType requestObject, XMLServiceCallback<SetStorePreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetStorePreferencesResponseType.class);
    }

    /**
     public method
    */
    public void setTaxTable(SetTaxTableRequestType requestObject, XMLServiceCallback<SetTaxTableResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetTaxTableResponseType.class);
    }

    /**
     public method
    */
    public void setUserNotes(SetUserNotesRequestType requestObject, XMLServiceCallback<SetUserNotesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetUserNotesResponseType.class);
    }

    /**
     public method
    */
    public void setUserPreferences(SetUserPreferencesRequestType requestObject, XMLServiceCallback<SetUserPreferencesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SetUserPreferencesResponseType.class);
    }

    /**
     public method
    */
    public void uploadSiteHostedPictures(UploadSiteHostedPicturesRequestType requestObject, XMLServiceCallback<UploadSiteHostedPicturesResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, UploadSiteHostedPicturesResponseType.class);
    }

    /**
     public method
    */
    public void validateChallengeInput(ValidateChallengeInputRequestType requestObject, XMLServiceCallback<ValidateChallengeInputResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ValidateChallengeInputResponseType.class);
    }

    /**
     public method
    */
    public void validateTestUserRegistration(ValidateTestUserRegistrationRequestType requestObject, XMLServiceCallback<ValidateTestUserRegistrationResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ValidateTestUserRegistrationResponseType.class);
    }

    /**
     public method
    */
    public void veROReportItems(VeROReportItemsRequestType requestObject, XMLServiceCallback<VeROReportItemsResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, VeROReportItemsResponseType.class);
    }

    /**
     public method
    */
    public void verifyAddFixedPriceItem(VerifyAddFixedPriceItemRequestType requestObject, XMLServiceCallback<VerifyAddFixedPriceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, VerifyAddFixedPriceItemResponseType.class);
    }

    /**
     public method
    */
    public void verifyAddItem(VerifyAddItemRequestType requestObject, XMLServiceCallback<VerifyAddItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, VerifyAddItemResponseType.class);
    }

    /**
     public method
    */
    public void verifyAddSecondChanceItem(VerifyAddSecondChanceItemRequestType requestObject, XMLServiceCallback<VerifyAddSecondChanceItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, VerifyAddSecondChanceItemResponseType.class);
    }

    /**
     public method
    */
    public void verifyRelistItem(VerifyRelistItemRequestType requestObject, XMLServiceCallback<VerifyRelistItemResponseType> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, VerifyRelistItemResponseType.class);
    }


}