// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigInteger;
import com.amazon.webservices.awsecommerceservice._2011_08_01.bin.BinParameter;
import java.util.List;

@RootElement(name = "Bin", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class Bin implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "BinName")
	public String binName;	
	
	@Element(name = "BinItemCount")
	public BigInteger binItemCount;	
	
	@Element(name = "BinParameter")
	public List<BinParameter> binParameter;	
	
    
}