// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "CorrectedQuery", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class CorrectedQuery implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Keywords")
	public String keywords;	
	
	@Element(name = "Message")
	public String message;	
	
    
}