// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import com.amazon.webservices.awsecommerceservice._2011_08_01.item.ImageSets;
import com.amazon.webservices.awsecommerceservice._2011_08_01.item.AlternateVersions;
import java.util.List;
import com.amazon.webservices.awsecommerceservice._2011_08_01.item.Subjects;
import com.amazon.webservices.awsecommerceservice._2011_08_01.item.VariationAttributes;

@RootElement(name = "Item", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class Item implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ASIN")
	public String asin;	
	
	@Element(name = "ParentASIN")
	public String parentASIN;	
	
	@Element(name = "Errors")
	public Errors errors;	
	
	@Element(name = "DetailPageURL")
	public String detailPageURL;	
	
	@Element(name = "ItemLinks")
	public ItemLinks itemLinks;	
	
	@Element(name = "SalesRank")
	public String salesRank;	
	
	@Element(name = "SmallImage")
	public Image smallImage;	
	
	@Element(name = "MediumImage")
	public Image mediumImage;	
	
	@Element(name = "LargeImage")
	public Image largeImage;	
	
	@Element(name = "ImageSets")
	public List<ImageSets> imageSets;	
	
	@Element(name = "ItemAttributes")
	public ItemAttributes itemAttributes;	
	
	@Element(name = "VariationAttributes")
	public VariationAttributes variationAttributes;	
	
	@Element(name = "RelatedItems")
	public List<RelatedItems> relatedItems;	
	
	@Element(name = "Collections")
	public Collections collections;	
	
	@Element(name = "Subjects")
	public Subjects subjects;	
	
	@Element(name = "OfferSummary")
	public OfferSummary offerSummary;	
	
	@Element(name = "Offers")
	public Offers offers;	
	
	@Element(name = "VariationSummary")
	public VariationSummary variationSummary;	
	
	@Element(name = "Variations")
	public Variations variations;	
	
	@Element(name = "CustomerReviews")
	public CustomerReviews customerReviews;	
	
	@Element(name = "EditorialReviews")
	public EditorialReviews editorialReviews;	
	
	@Element(name = "SimilarProducts")
	public SimilarProducts similarProducts;	
	
	@Element(name = "Accessories")
	public Accessories accessories;	
	
	@Element(name = "Tracks")
	public Tracks tracks;	
	
	@Element(name = "BrowseNodes")
	public BrowseNodes browseNodes;	
	
	@Element(name = "AlternateVersions")
	public AlternateVersions alternateVersions;	
	
    
}