// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigInteger;
import java.util.List;

@RootElement(name = "Offers", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class Offers implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "TotalOffers")
	public BigInteger totalOffers;	
	
	@Element(name = "TotalOfferPages")
	public BigInteger totalOfferPages;	
	
	@Element(name = "MoreOffersUrl")
	public String moreOffersUrl;	
	
	@Element(name = "Offer")
	public List<Offer> offer;	
	
    
}