// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "OperationRequest", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class OperationRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "HTTPHeaders")
	@Order(value=0)
	public HTTPHeaders httpHeaders;	
	
	@Element(name = "RequestId")
	@Order(value=1)
	public String requestId;	
	
	@Element(name = "Arguments")
	@Order(value=2)
	public Arguments arguments;	
	
	@Element(name = "Errors")
	@Order(value=3)
	public Errors errors;	
	
	@Element(name = "RequestProcessingTime")
	@Order(value=4)
	public Float requestProcessingTime;	
	
    
}