// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.itemattributes.languages;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class Language implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Name")
	public String name;	
	
	@Element(name = "Type")
	public String type;	
	
	@Element(name = "AudioFormat")
	public String audioFormat;	
	
    
}