// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.webservicemart.ws.client;


import com.leansoft.nano.ws.XMLServiceCallback;
import com.leansoft.nano.ws.NanoXMLClient;
import com.webservicemart.ws.ValidateZipResponse;
import com.webservicemart.ws.ValidateZip;


/**
 This class is the XML client to the USZipSoap Web Service.
*/ 
public class USZipSoap_XMLClient extends NanoXMLClient {


    /**
     Returns United States Postal Service State Abbreviation, Latitude (decimal degrees) and Longitude (decimal degrees).
    */
    public void validateZip(ValidateZip requestObject, XMLServiceCallback<ValidateZipResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ValidateZipResponse.class);
    }


}