// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.cartitem;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import com.amazon.webservices.awsecommerceservice._2011_08_01.cartitem.metadata.KeyValuePair;
import java.util.List;

public class MetaData implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "KeyValuePair")
	public List<KeyValuePair> keyValuePair;	
	
    
}