// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Base type definition of a response payload that can carry any
 * type of payload content with following optional elements:<br>
 * - timestamp of response message<br>
 * - application-level acknowledgement<br>
 * - application-level (business-level) errors and warnings
 * 
 */
public abstract class AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Timestamp")
	public Date timestamp;	
	
	@Element(name = "Ack")
	public AckCodeType ack;	
	
	@Element(name = "Errors")
	public List<ErrorType> errors;	
	
	@Element(name = "Build")
	public String build;	
	
	@Element(name = "Version")
	public String version;	
	
	@Element(name = "CorrelationID")
	public String correlationID;	
	
	@AnyElement
	public List<Object> any;	
	
    
}