// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the data for one user address. This is the base type for a
 * number of user addresses, including seller payment address, buyer
 * shipping address and buyer and seller registration address.
 * 
 */
public class AddressType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Name")
	public String name;	
	
	@Element(name = "Street")
	public String street;	
	
	@Element(name = "Street1")
	public String street1;	
	
	@Element(name = "Street2")
	public String street2;	
	
	@Element(name = "CityName")
	public String cityName;	
	
	@Element(name = "County")
	public String county;	
	
	@Element(name = "StateOrProvince")
	public String stateOrProvince;	
	
	@Element(name = "CountryName")
	public String countryName;	
	
	@Element(name = "Phone")
	public String phone;	
	
	@Element(name = "PhoneCountryPrefix")
	public String phoneCountryPrefix;	
	
	@Element(name = "PhoneAreaOrCityCode")
	public String phoneAreaOrCityCode;	
	
	@Element(name = "PhoneLocalNumber")
	public String phoneLocalNumber;	
	
	@Element(name = "Phone2CountryPrefix")
	public String phone2CountryPrefix;	
	
	@Element(name = "Phone2AreaOrCityCode")
	public String phone2AreaOrCityCode;	
	
	@Element(name = "Phone2LocalNumber")
	public String phone2LocalNumber;	
	
	@Element(name = "PostalCode")
	public String postalCode;	
	
	@Element(name = "AddressID")
	public String addressID;	
	
	@Element(name = "ExternalAddressID")
	public String externalAddressID;	
	
	@Element(name = "InternationalName")
	public String internationalName;	
	
	@Element(name = "InternationalStateAndCity")
	public String internationalStateAndCity;	
	
	@Element(name = "InternationalStreet")
	public String internationalStreet;	
	
	@Element(name = "CompanyName")
	public String companyName;	
	
	@Element(name = "FirstName")
	public String firstName;	
	
	@Element(name = "LastName")
	public String lastName;	
	
	@AnyElement
	public List<Object> any;	
	
    
}