// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * A generic type used for histograms.
 * 
 */
public class DomainHistogramType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Domain")
	public List<HistogramEntryType> domain;	
	
	@AnyElement
	public List<Object> any;	
	
    
}