// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the data for one type of feedback for one predefined time
 * period. Parent FeedbackPeriodArrayType object indicates the type of
 * feedback counted: positive, neutral, negative, or total. 
 * 
 */
public class FeedbackPeriodType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PeriodInDays")
	public Integer periodInDays;	
	
	@Element(name = "Count")
	public Long count;	
	
	@AnyElement
	public List<Object> any;	
	
    
}