// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Response to GetSingleItem request.
 * 
 */
@RootElement(name = "GetSingleItemResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSingleItemResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Item")
	public SimpleItemType item;	
	
    
}