// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

/**
 * 
 * Specifies an active or ended listing's status in eBay's processing
 * workflow. If a listing ends with a sale (or sales), eBay needs to
 * update the sale details (e.g., total price and buyer/high bidder)
 * and the final value fee. This processing can take several minutes.
 * If you retrieve a sold item and no details about the buyer/high
 * bidder are returned, use this
 * listing status information to determine whether eBay has finished
 * processing the listing.
 * 
 */
public enum ListingStatusCodeType {

    /**
     * 
   * (out) The listing is still live, or it has recently ended
   * but eBay has not completed processing
   * the listing (e.g., we're still determining the high bidder).
   * A multi-item listing is considered active until all items
   * have winning bids or purchases or the listing's end time
   * has passed. (That is, if the listing has a Quantity of 10,
   * the sale of 1 of those items doesn't end the listing.)
   * If the listing has ended but this Active
   * status is returned, please allow several minutes for eBay to
   * finish processing the listing.
   * 
     */
    ACTIVE("Active"),
  

    /**
     * 
   * (out) The listing has ended and eBay has completed processing
   * of the sale (if any), such as determining the high bidder.
   * 
     */
    ENDED("Ended"),
  

    /**
     * 
   * (out) The listing has ended and eBay has completed processing
   * of the sale (if any), such as determining the high bidder.
   * You can think of Completed and Ended as essentially equivalent.
   * (The difference is only meaningful to the seller of the item,
   * as Completed indicates whether eBay has finished calculating
   * certain selling fees.)
   * 
     */
    COMPLETED("Completed"),
  

    /**
     * 
   * (out) Placeholder value. See
   * <a href="types/simpleTypes.html#token">token</a>.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    ListingStatusCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ListingStatusCodeType fromValue(String v) {
        if (v != null) {
            for (ListingStatusCodeType c: ListingStatusCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}