// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Product ID has an attribute of ProductIDCodeType and a string value.
 * 
 */
public class ProductIDType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	public String value;	
	
	@Attribute  
	public ProductIDCodeType type;	
	
    
}