// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type for the return policy details of an item.
 * 
 */
public class ReturnPolicyType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Refund")
	public String refund;	
	
	@Element(name = "ReturnsWithin")
	public String returnsWithin;	
	
	@Element(name = "ReturnsAccepted")
	public String returnsAccepted;	
	
	@Element(name = "Description")
	public String description;	
	
	@Element(name = "WarrantyOffered")
	public String warrantyOffered;	
	
	@Element(name = "WarrantyType")
	public String warrantyType;	
	
	@Element(name = "WarrantyDuration")
	public String warrantyDuration;	
	
	@Element(name = "EAN")
	public String ean;	
	
	@Element(name = "ShippingCostPaidBy")
	public String shippingCostPaidBy;	
	
	@Element(name = "RestockingFeeValue")
	public String restockingFeeValue;	
	
	@Element(name = "RestockingFeeValueOption")
	public String restockingFeeValueOption;	
	
	@AnyElement
	public List<Object> any;	
	
    
}