// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type for the shipping-related details for an item or transaction.
 * 
 */
public class ShippingDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "GetItFast")
	@Order(value=0)
	public Boolean getItFast;	
	
	@Element(name = "InsuranceCost")
	@Order(value=1)
	public AmountType insuranceCost;	
	
	@Element(name = "InsuranceOption")
	@Order(value=2)
	public InsuranceOptionCodeType insuranceOption;	
	
	@Element(name = "InternationalShippingServiceOption")
	@Order(value=3)
	public List<InternationalShippingServiceOptionType> internationalShippingServiceOption;	
	
	@Element(name = "SalesTax")
	@Order(value=4)
	public SalesTaxType salesTax;	
	
	@Element(name = "ShippingRateErrorMessage")
	@Order(value=5)
	public String shippingRateErrorMessage;	
	
	@Element(name = "ShippingServiceOption")
	@Order(value=6)
	public List<ShippingServiceOptionType> shippingServiceOption;	
	
	@Element(name = "TaxTable")
	@Order(value=7)
	public TaxTableType taxTable;	
	
	@Element(name = "InternationalInsuranceCost")
	@Order(value=8)
	public AmountType internationalInsuranceCost;	
	
	@Element(name = "InternationalInsuranceOption")
	@Order(value=9)
	public InsuranceOptionCodeType internationalInsuranceOption;	
	
	@Element(name = "CODCost")
	@Order(value=10)
	public AmountType codCost;	
	
	@Element(name = "ExcludeShipToLocation")
	@Order(value=11)
	public List<String> excludeShipToLocation;	
	
	@AnyElement
	@Order(value=12)
	public List<Object> any;	
	
    
}