//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.05 at 03:39:55 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.leansoft.com/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.leansoft.jaxb.person;
