// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package ebay.apis.eblbasecomponents.client;


import com.leansoft.nano.ws.ServiceCallback;
import com.leansoft.nano.ws.NanoXMLClient;
import ebay.apis.eblbasecomponents.GetSingleItemResponseType;
import ebay.apis.eblbasecomponents.GetShippingCostsResponseType;
import ebay.apis.eblbasecomponents.GetCategoryInfoResponseType;
import ebay.apis.eblbasecomponents.GeteBayTimeRequestType;
import ebay.apis.eblbasecomponents.GetCategoryInfoRequestType;
import ebay.apis.eblbasecomponents.GetUserProfileRequestType;
import ebay.apis.eblbasecomponents.GetUserProfileResponseType;
import ebay.apis.eblbasecomponents.GetSingleItemRequestType;
import ebay.apis.eblbasecomponents.FindPopularSearchesRequestType;
import ebay.apis.eblbasecomponents.FindHalfProductsResponseType;
import ebay.apis.eblbasecomponents.FindPopularItemsRequestType;
import ebay.apis.eblbasecomponents.FindReviewsAndGuidesRequestType;
import ebay.apis.eblbasecomponents.FindPopularSearchesResponseType;
import ebay.apis.eblbasecomponents.FindProductsResponseType;
import ebay.apis.eblbasecomponents.GeteBayTimeResponseType;
import ebay.apis.eblbasecomponents.GetMultipleItemsResponseType;
import ebay.apis.eblbasecomponents.GetShippingCostsRequestType;
import ebay.apis.eblbasecomponents.GetItemStatusResponseType;
import ebay.apis.eblbasecomponents.FindPopularItemsResponseType;
import ebay.apis.eblbasecomponents.GetMultipleItemsRequestType;
import ebay.apis.eblbasecomponents.FindProductsRequestType;
import ebay.apis.eblbasecomponents.FindReviewsAndGuidesResponseType;
import ebay.apis.eblbasecomponents.FindHalfProductsRequestType;
import ebay.apis.eblbasecomponents.GetItemStatusRequestType;


/**
 This class is the XML client to the ShoppingInterface Web Service.
*/ 
public class ShoppingInterface_XMLClient extends NanoXMLClient {


    /**
     public method
    */
    public void findHalfProducts(FindHalfProductsRequestType requestObject, ServiceCallback<FindHalfProductsResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "FindHalfProducts");
        
        super.invoke(requestObject, serviceCallback, FindHalfProductsResponseType.class);
    }

    /**
     public method
    */
    public void findPopularItems(FindPopularItemsRequestType requestObject, ServiceCallback<FindPopularItemsResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "FindPopularItems");
        
        super.invoke(requestObject, serviceCallback, FindPopularItemsResponseType.class);
    }

    /**
     public method
    */
    public void findPopularSearches(FindPopularSearchesRequestType requestObject, ServiceCallback<FindPopularSearchesResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "FindPopularSearches");
        
        super.invoke(requestObject, serviceCallback, FindPopularSearchesResponseType.class);
    }

    /**
     public method
    */
    public void findProducts(FindProductsRequestType requestObject, ServiceCallback<FindProductsResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "FindProducts");
        
        super.invoke(requestObject, serviceCallback, FindProductsResponseType.class);
    }

    /**
     public method
    */
    public void findReviewsAndGuides(FindReviewsAndGuidesRequestType requestObject, ServiceCallback<FindReviewsAndGuidesResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "FindReviewsAndGuides");
        
        super.invoke(requestObject, serviceCallback, FindReviewsAndGuidesResponseType.class);
    }

    /**
     public method
    */
    public void getCategoryInfo(GetCategoryInfoRequestType requestObject, ServiceCallback<GetCategoryInfoResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetCategoryInfo");
        
        super.invoke(requestObject, serviceCallback, GetCategoryInfoResponseType.class);
    }

    /**
     public method
    */
    public void getItemStatus(GetItemStatusRequestType requestObject, ServiceCallback<GetItemStatusResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetItemStatus");
        
        super.invoke(requestObject, serviceCallback, GetItemStatusResponseType.class);
    }

    /**
     public method
    */
    public void getMultipleItems(GetMultipleItemsRequestType requestObject, ServiceCallback<GetMultipleItemsResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetMultipleItems");
        
        super.invoke(requestObject, serviceCallback, GetMultipleItemsResponseType.class);
    }

    /**
     public method
    */
    public void getShippingCosts(GetShippingCostsRequestType requestObject, ServiceCallback<GetShippingCostsResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetShippingCosts");
        
        super.invoke(requestObject, serviceCallback, GetShippingCostsResponseType.class);
    }

    /**
     public method
    */
    public void getSingleItem(GetSingleItemRequestType requestObject, ServiceCallback<GetSingleItemResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetSingleItem");
        
        super.invoke(requestObject, serviceCallback, GetSingleItemResponseType.class);
    }

    /**
     public method
    */
    public void getUserProfile(GetUserProfileRequestType requestObject, ServiceCallback<GetUserProfileResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GetUserProfile");
        
        super.invoke(requestObject, serviceCallback, GetUserProfileResponseType.class);
    }

    /**
     public method
    */
    public void geteBayTime(GeteBayTimeRequestType requestObject, ServiceCallback<GeteBayTimeResponseType> serviceCallback) {
       
        super.getAsyncHttpClient().addHeader("X-EBAY-API-CALL-NAME", "GeteBayTime");
        
        super.invoke(requestObject, serviceCallback, GeteBayTimeResponseType.class);
    }


}