// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.topitemset;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

public class TopItem implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ASIN")
	public String asin;	
	
	@Element(name = "Title")
	public String title;	
	
	@Element(name = "DetailPageURL")
	public String detailPageURL;	
	
	@Element(name = "ProductGroup")
	public String productGroup;	
	
	@Element(name = "Author")
	public List<String> author;	
	
	@Element(name = "Artist")
	public List<String> artist;	
	
	@Element(name = "Actor")
	public List<String> actor;	
	
    
}