// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Enables a buyer and seller in an order relationship to
 * send messages to each other's My Messages Inboxes.
 * 
 */
@RootElement(name = "AddMemberMessageAAQToPartnerRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddMemberMessageAAQToPartnerRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "MemberMessage")
	@Order(value=1)
	public MemberMessageType memberMessage;	
	
    
}