// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Enumerated type that defines the eBay user's account type.
 * 
 */
public enum BusinessRoleType {

    /**
     * 
   * This value indicates that the eBay user's account is a Partially Provisioned Account
   * without buying and selling privileges on eBay.
   * 
     */
    SHOPPER("Shopper"),
  

    /**
     * 
   * This value indicates that the eBay user's account is a fully provisioned account with buying
   * and selling privileges on eBay.
   * 
     */
    FULL_MARKET_PLACE_PARTICIPANT("FullMarketPlaceParticipant");
  
  
    private final String value;
  
    BusinessRoleType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static BusinessRoleType fromValue(String v) {
        if (v != null) {
            for (BusinessRoleType c: BusinessRoleType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}