// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * All Best Offers for the item according to the filter or Best Offer
 * ID (or both) used in the input.
 * For the notification client usage, this response includes a
 * single Best Offer.
 * 
 */
@RootElement(name = "GetBestOffersResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetBestOffersResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "BestOfferArray")
	@Order(value=0)
	public BestOfferArrayType bestOfferArray;	
	
	@Element(name = "Item")
	@Order(value=1)
	public ItemType item;	
	
	@Element(name = "ItemBestOffersArray")
	@Order(value=2)
	public ItemBestOffersArrayType itemBestOffersArray;	
	
	@Element(name = "PageNumber")
	@Order(value=3)
	public Integer pageNumber;	
	
	@Element(name = "PaginationResult")
	@Order(value=4)
	public PaginationResultType paginationResult;	
	
    
}