// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Retrieves a botblock token and URLs for an image or audio clip that the user is to
 * match.
 * 
 */
@RootElement(name = "GetChallengeTokenRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetChallengeTokenRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}