// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the requesting application's notification preferences.
 * GetNotificationPreferences retrieves preferences that you have
 * deliberately set. For example, if you enable the EndOfAuction event and
 * then later disable it, the response shows the EndOfAuction event
 * preference as Disabled. But if you have never set a preference for the
 * EndOfAuction event, no EndOfAuction preference is returned at all.
 * 
 */
@RootElement(name = "GetNotificationPreferencesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetNotificationPreferencesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ApplicationDeliveryPreferences")
	@Order(value=0)
	public ApplicationDeliveryPreferencesType applicationDeliveryPreferences;	
	
	@Element(name = "DeliveryURLName")
	@Order(value=1)
	public String deliveryURLName;	
	
	@Element(name = "UserDeliveryPreferenceArray")
	@Order(value=2)
	public NotificationEnableArrayType userDeliveryPreferenceArray;	
	
	@Element(name = "UserData")
	@Order(value=3)
	public NotificationUserDataType userData;	
	
	@Element(name = "EventProperty")
	@Order(value=4)
	public List<NotificationEventPropertyType> eventProperty;	
	
    
}