// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Defines the system source for an Item Specific.
 * 
 */
public enum ItemSpecificSourceCodeType {

    /**
     * 
   * The Item Specific was originally stored with custom
   * Item Specifics fields. (For example, the seller used
   * the ItemSpecifics node in AddItem.)
   * This is the default setting if Source isn't returned.
   * 
     */
    ITEM_SPECIFIC("ItemSpecific"),
  

    /**
     * 
   * The Item Specific was originally stored with eBay's
   * system-defined (ID-based) attributes format. (For example,
   * the seller used the AttributeSetArray node in AddItem
   * at a time when the category supported Attributes.)
   * 
     */
    ATTRIBUTE("Attribute"),
  

    /**
     * 
   * The Item Specific is prefilled from a product catalog. (For example,
   * the seller used ExternalProductID or ProductID in AddItem.)
   * 
     */
    PRODUCT("Product"),
  

    /**
     * 
   * Reserved for future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    ItemSpecificSourceCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ItemSpecificSourceCodeType fromValue(String v) {
        if (v != null) {
            for (ItemSpecificSourceCodeType c: ItemSpecificSourceCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}