// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Container for a list of items. Can contain zero, one, or multiple
 * ItemType objects, each of which conveys the data for one item listing.
 * 
 */
public class ItemArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Item")
	@Order(value=0)
	public List<ItemType> item;	
	
    
}