// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Defines the LocalListingDistancesRegular feature. This feature displays all the supported local listing
 * distances for items listed by sellers subscribed to Local Market for Vehicles.
 * 
 */
public class LocalListingDistancesRegularDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

	@AnyElement
	@Order(value=0)
	public List<Object> any;	
	
    
}