// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

public enum OrderStatusFilterCodeType {

    /**
     * 
   * All applicable sold listings, regardless of
   * their Paid or Shipped status.
   * 
     */
    ALL("All"),
  

    /**
     * 
   * Sold listings that have not yet been marked as
   * Paid in My eBay.
   * 
     */
    AWAITING_PAYMENT("AwaitingPayment"),
  

    /**
     * 
   * Sold listings that have not yet been marked as
   * Shipped in My eBay.
   * 
     */
    AWAITING_SHIPMENT("AwaitingShipment"),
  

    /**
     * 
   * Sold listings that have been marked as
   * Paid and Shipped in My eBay.
   * 
     */
    PAID_AND_SHIPPED("PaidAndShipped"),
  

    /**
     * 
   * Reserved for future or internal use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    OrderStatusFilterCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static OrderStatusFilterCodeType fromValue(String v) {
        if (v != null) {
            for (OrderStatusFilterCodeType c: OrderStatusFilterCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}