// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Defines rules for recommended Item Specifics. The rules apply when
 * the Item Specific is subsequently used in AddItem and related calls.
 * 
 */
public class RecommendationValidationRulesType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ValueType")
	@Order(value=0)
	public ValueTypeCodeType valueType;	
	
	@Element(name = "MinValues")
	@Order(value=1)
	public Integer minValues;	
	
	@Element(name = "MaxValues")
	@Order(value=2)
	public Integer maxValues;	
	
	@Element(name = "SelectionMode")
	@Order(value=3)
	public SelectionModeCodeType selectionMode;	
	
	@Element(name = "Confidence")
	@Order(value=4)
	public Integer confidence;	
	
	@Element(name = "Relationship")
	@Order(value=5)
	public List<NameValueRelationshipType> relationship;	
	
	@Element(name = "VariationPicture")
	@Order(value=6)
	public VariationPictureRuleCodeType variationPicture;	
	
	@Element(name = "VariationSpecifics")
	@Order(value=7)
	public VariationSpecificsRuleCodeType variationSpecifics;	
	
	@Element(name = "ValueFormat")
	@Order(value=8)
	public ValueFormatCodeType valueFormat;	
	
	@AnyElement
	@Order(value=9)
	public List<Object> any;	
	
    
}