// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * This type is deprecated as <b>GetProduct*</b> calls were deprecated.
 * 
 * 
 */
public class ResponseAttributeSetType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ApproximatePages")
	@Order(value=0)
	public int approximatePages;	
	
	@Element(name = "AttributeSetID")
	@Order(value=1)
	public int attributeSetID;	
	
	@Element(name = "HasMore")
	@Order(value=2)
	public boolean hasMore;	
	
	@Element(name = "ProductFamilies")
	@Order(value=3)
	public List<ProductFamilyType> productFamilies;	
	
	@Element(name = "ProductFinderConstraints")
	@Order(value=4)
	public List<ProductFinderConstraintType> productFinderConstraints;	
	
	@Element(name = "TooManyMatchesFound")
	@Order(value=5)
	public boolean tooManyMatchesFound;	
	
	@Element(name = "TotalProducts")
	@Order(value=6)
	public int totalProducts;	
	
	@AnyElement
	@Order(value=7)
	public List<Object> any;	
	
    
}