// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Returns the Item ID or SKU with changed Price and Quantity for the revised listing.
 * 
 */
@RootElement(name = "ReviseInventoryStatusResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ReviseInventoryStatusResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "InventoryStatus")
	@Order(value=0)
	public List<InventoryStatusType> inventoryStatus;	
	
	@Element(name = "Fees")
	@Order(value=1)
	public List<InventoryFeesType> fees;	
	
    
}