// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Maximum level of guarantee a seller is authorized to offer.
 * 
 */
public enum SellerGuaranteeLevelCodeType {

    /**
     * 
   * (out) Not eligible for Seller Level Guarantee
   * 
     */
    NOT_ELIGIBLE("NotEligible"),
  

    /**
     * 
   * (out) Regular eligibility level
   * 
     */
    REGULAR("Regular"),
  

    /**
     * 
   * (out) Premium eligibility level
   * 
     */
    PREMIUM("Premium"),
  

    /**
     * 
   * (out) Ultra eligibility level
   * 
     */
    ULTRA("Ultra"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    SellerGuaranteeLevelCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static SellerGuaranteeLevelCodeType fromValue(String v) {
        if (v != null) {
            for (SellerGuaranteeLevelCodeType c: SellerGuaranteeLevelCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}