// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Describes a Selling Manager Template
 * 
 */
public class SellingManagerProductSpecificsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PrimaryCategoryID")
	@Order(value=0)
	public String primaryCategoryID;	
	
	@Element(name = "Variations")
	@Order(value=1)
	public VariationsType variations;	
	
	@Element(name = "ItemSpecifics")
	@Order(value=2)
	public NameValueListArrayType itemSpecifics;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}