// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Enables a seller to send an order invoice to a buyer. Where applicable, updates to shipping, payment methods, and sales tax made in this request are applied to the specified order as a whole and to the individual order line items whose data are stored in individual <b>Transaction</b> objects.
 * 
 */
@RootElement(name = "SendInvoiceRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SendInvoiceRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "TransactionID")
	@Order(value=1)
	public String transactionID;	
	
	@Element(name = "OrderID")
	@Order(value=2)
	public String orderID;	
	
	@Element(name = "InternationalShippingServiceOptions")
	@Order(value=3)
	public List<InternationalShippingServiceOptionsType> internationalShippingServiceOptions;	
	
	@Element(name = "ShippingServiceOptions")
	@Order(value=4)
	public List<ShippingServiceOptionsType> shippingServiceOptions;	
	
	@Element(name = "SalesTax")
	@Order(value=5)
	public SalesTaxType salesTax;	
	
	@Element(name = "InsuranceOption")
	@Order(value=6)
	public InsuranceOptionCodeType insuranceOption;	
	
	@Element(name = "InsuranceFee")
	@Order(value=7)
	public AmountType insuranceFee;	
	
	@Element(name = "PaymentMethods")
	@Order(value=8)
	public List<BuyerPaymentMethodCodeType> paymentMethods;	
	
	@Element(name = "PayPalEmailAddress")
	@Order(value=9)
	public String payPalEmailAddress;	
	
	@Element(name = "CheckoutInstructions")
	@Order(value=10)
	public String checkoutInstructions;	
	
	@Element(name = "EmailCopyToSeller")
	@Order(value=11)
	public Boolean emailCopyToSeller;	
	
	@Element(name = "CODCost")
	@Order(value=12)
	public AmountType codCost;	
	
	@Element(name = "SKU")
	@Order(value=13)
	public String sku;	
	
	@Element(name = "OrderLineItemID")
	@Order(value=14)
	public String orderLineItemID;	
	
    
}