// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * (out) Returns the success or failure of a SetNotificationPreferences request.
 * 
 */
@RootElement(name = "SetNotificationPreferencesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetNotificationPreferencesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}