// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Packages supported by the enclosing shipping service.
 * 
 */
public class ShippingServicePackageDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Name")
	@Order(value=0)
	public ShippingPackageCodeType name;	
	
	@Element(name = "DimensionsRequired")
	@Order(value=1)
	public Boolean dimensionsRequired;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
    
}