// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Store theme.
 * 
 */
public class StoreThemeType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ThemeID")
	@Order(value=0)
	public Integer themeID;	
	
	@Element(name = "Name")
	@Order(value=1)
	public String name;	
	
	@Element(name = "ColorScheme")
	@Order(value=2)
	public StoreColorSchemeType colorScheme;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}