// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Units of measure that you can use to specify properties such as weight and size
 * dimensions.
 * 
 */
public enum UnitCodeType {

    /**
     * 
   * Kilograms
   * 
     */
    KG("kg"),
  

    /**
     * 
   * Grams
   * 
     */
    GM("gm"),
  

    /**
     * 
   * Pounds
   * 
     */
    LBS("lbs"),
  

    /**
     * 
   * Ounces
   * 
     */
    OZ("oz"),
  

    /**
     * 
   * Centimeters
   * 
     */
    CM("cm"),
  

    /**
     * 
   * Milimeters
   * 
     */
    MM("mm"),
  

    /**
     * 
   * Inches
   * 
     */
    INCHES("inches"),
  

    /**
     * 
   * Feet
   * 
     */
    FT("ft"),
  

    /**
     * 
   * Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    UnitCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static UnitCodeType fromValue(String v) {
        if (v != null) {
            for (UnitCodeType c: UnitCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}