// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.othercategoriessimilarproducts;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class OtherCategoriesSimilarProduct implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ASIN")
	public String asin;	
	
	@Element(name = "Title")
	public String title;	
	
    
}