// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.dataaccess.webservicesserver;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;

@RootElement(name = "NumberToDollars", namespace = "http://www.dataaccess.com/webservicesserver/")
public class NumberToDollars implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public BigDecimal dNum;	
	
    
}