// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.shopping.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Basic type for specifying monetary amounts. A double value (e.g.,
 * 1.00 or 1.0) is meaningful as a monetary amount when accompanied by a
 * specification of the currency, in which case the value specifies
 * the amount in that currency. An AmountType expresses both the value
 * (a double) and the currency. Details such as prices, fees, costs,
 * and payments are specified as amount types.
 * 
 */
public class AmountType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	@Order(value=0)
	public double value;	
	
	@Attribute  
	@Order(value=1)
	public CurrencyCodeType currencyID;	
	
    
}