// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.shopping.api;

/**
 * 
 *  FeedbackRatingStarCodeType - Type declaration to be used by other
 *  schema. The color of a feedback score star visually denotes the
 *  range in which the member's summary feedback score falls. The score
 *  is the net positive feedback minus the net negative feedback left
 *  for the member.
 * 
 */
public enum FeedbackRatingStarCodeType {

    /**
     * 
   * No graphic displayed, feedback score 0-9.
   * 
     */
    NONE("None"),
  

    /**
     * 
   * Yellow Star, feedback score 10-49.
   * 
     */
    YELLOW("Yellow"),
  

    /**
     * 
   * Blue Star, feedback score 50-99.
   * 
     */
    BLUE("Blue"),
  

    /**
     * 
   * Turquoise Star, feedback score 100-499.
   * 
     */
    TURQUOISE("Turquoise"),
  

    /**
     * 
   * Purple Star, feedback score 500-999.
   * 
     */
    PURPLE("Purple"),
  

    /**
     * 
   * Red Star, feedback score 1,000-4,999
   * 
     */
    RED("Red"),
  

    /**
     * 
   * Green Star, feedback score 5,000-9,999.
   * 
     */
    GREEN("Green"),
  

    /**
     * 
   * Yellow Shooting Star, feedback score 10,000-24,999.
   * 
     */
    YELLOW_SHOOTING("YellowShooting"),
  

    /**
     * 
   * Turquoise Shooting Star, feedback score 25,000-49,999.
   * 
     */
    TURQUOISE_SHOOTING("TurquoiseShooting"),
  

    /**
     * 
   * Purple Shooting Star, feedback score 50,000-99,999.
   * 
     */
    PURPLE_SHOOTING("PurpleShooting"),
  

    /**
     * 
   * Red Shooting Star, feedback score 100,000-499,999.
   * 
     */
    RED_SHOOTING("RedShooting"),
  

    /**
     * 
   * Green Shooting Star, feedback score 500,000-900,000.
   * 
     */
    GREEN_SHOOTING("GreenShooting"),
  

    /**
     * 
   * Silver Shooting Star, feedback score 1,000,000 and above.
   * 
     */
    SILVER_SHOOTING("SilverShooting"),
  

    /**
     * 
   * Placeholder value. See
   * <a href="types/simpleTypes.html#token">token</a>.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    FeedbackRatingStarCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static FeedbackRatingStarCodeType fromValue(String v) {
        if (v != null) {
            for (FeedbackRatingStarCodeType c: FeedbackRatingStarCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}