// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.shopping.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Returns stock product information in eBay catalogs, such as
 * information about a particular DVD or camera. Optionally,
 * also returns items that match the product.
 * 
 */
@RootElement(name = "FindProductsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class FindProductsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ApproximatePages")
	@Order(value=0)
	public Integer approximatePages;	
	
	@Element(name = "MoreResults")
	@Order(value=1)
	public Boolean moreResults;	
	
	@Element(name = "DomainHistogram")
	@Order(value=2)
	public DomainHistogramType domainHistogram;	
	
	@Element(name = "ItemArray")
	@Order(value=3)
	public SimpleItemArrayType itemArray;	
	
	@Element(name = "PageNumber")
	@Order(value=4)
	public Integer pageNumber;	
	
	@Element(name = "Product")
	@Order(value=5)
	public List<CatalogProductType> product;	
	
	@Element(name = "TotalProducts")
	@Order(value=6)
	public Integer totalProducts;	
	
	@Element(name = "DuplicateItems")
	@Order(value=7)
	public Boolean duplicateItems;	
	
    
}