// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.shopping.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type for the shipping-related details for an item or transaction.
 * 
 */
public class ShippingCostSummaryType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ShippingServiceName")
	@Order(value=0)
	public String shippingServiceName;	
	
	@Element(name = "ShippingServiceCost")
	@Order(value=1)
	public AmountType shippingServiceCost;	
	
	@Element(name = "InsuranceCost")
	@Order(value=2)
	public AmountType insuranceCost;	
	
	@Element(name = "ShippingType")
	@Order(value=3)
	public ShippingTypeCodeType shippingType;	
	
	@Element(name = "LocalPickup")
	@Order(value=4)
	public Boolean localPickup;	
	
	@Element(name = "InsuranceOption")
	@Order(value=5)
	public InsuranceOptionCodeType insuranceOption;	
	
	@Element(name = "ListedShippingServiceCost")
	@Order(value=6)
	public AmountType listedShippingServiceCost;	
	
	@Element(name = "ImportCharge")
	@Order(value=7)
	public AmountType importCharge;	
	
	@AnyElement
	@Order(value=8)
	public List<Object> any;	
	
    
}