// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.client;


import com.leansoft.nano.ws.ServiceCallback;
import com.leansoft.nano.ws.NanoXMLClient;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartClear;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartModify;
import com.amazon.webservices.awsecommerceservice._2011_08_01.SimilarityLookup;
import com.amazon.webservices.awsecommerceservice._2011_08_01.SimilarityLookupResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.ItemSearch;
import com.amazon.webservices.awsecommerceservice._2011_08_01.ItemSearchResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartClearResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartGet;
import com.amazon.webservices.awsecommerceservice._2011_08_01.ItemLookup;
import com.amazon.webservices.awsecommerceservice._2011_08_01.BrowseNodeLookup;
import com.amazon.webservices.awsecommerceservice._2011_08_01.ItemLookupResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartAdd;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartAddResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartGetResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartCreate;
import com.amazon.webservices.awsecommerceservice._2011_08_01.BrowseNodeLookupResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartCreateResponse;
import com.amazon.webservices.awsecommerceservice._2011_08_01.CartModifyResponse;


/**
 This class is the XML client to the AWSECommerceServicePortType Web Service.
*/ 
public class AWSECommerceServicePortType_XMLClient extends NanoXMLClient {


    /**
     public method
    */
    public void itemSearch(ItemSearch requestObject, ServiceCallback<ItemSearchResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ItemSearchResponse.class);
    }

    /**
     public method
    */
    public void itemLookup(ItemLookup requestObject, ServiceCallback<ItemLookupResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, ItemLookupResponse.class);
    }

    /**
     public method
    */
    public void browseNodeLookup(BrowseNodeLookup requestObject, ServiceCallback<BrowseNodeLookupResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, BrowseNodeLookupResponse.class);
    }

    /**
     public method
    */
    public void similarityLookup(SimilarityLookup requestObject, ServiceCallback<SimilarityLookupResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, SimilarityLookupResponse.class);
    }

    /**
     public method
    */
    public void cartGet(CartGet requestObject, ServiceCallback<CartGetResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CartGetResponse.class);
    }

    /**
     public method
    */
    public void cartCreate(CartCreate requestObject, ServiceCallback<CartCreateResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CartCreateResponse.class);
    }

    /**
     public method
    */
    public void cartAdd(CartAdd requestObject, ServiceCallback<CartAddResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CartAddResponse.class);
    }

    /**
     public method
    */
    public void cartModify(CartModify requestObject, ServiceCallback<CartModifyResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CartModifyResponse.class);
    }

    /**
     public method
    */
    public void cartClear(CartClear requestObject, ServiceCallback<CartClearResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, CartClearResponse.class);
    }


}