// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01.browsenode;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import com.amazon.webservices.awsecommerceservice._2011_08_01.Property;

public class Properties implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Property")
	public List<Property> property;	
	
    
}