// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * PayPal address status.
 * 
 */
public enum AddressStatusCodeType {

    NONE("None"),
  

    CONFIRMED("Confirmed"),
  

    UNCONFIRMED("Unconfirmed"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    AddressStatusCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static AddressStatusCodeType fromValue(String v) {
        if (v != null) {
            for (AddressStatusCodeType c: AddressStatusCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}