// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Used to indicate whether the Ad Format feature is enabled for a category.
 * 
 */
public enum AdFormatEnabledCodeType {

    /**
     * 
   * The Ad Format feature is disabled for the category.
   * 
     */
    DISABLED("Disabled"),
  

    /**
     * 
   * The Ad Format feature is enabled for the category.
   * 
     */
    ENABLED("Enabled"),
  

    /**
     * 
   * The category supports the Ad Format feature only.
   * 
     */
    ONLY("Only"),
  

    /**
     * 
   * The lead generation Classified Ad Format feature is enabled for the category.
   *   
     */
    CLASSIFIED_AD_ENABLED("ClassifiedAdEnabled"),
  

    /**
     * 
   * The category supports the lead generation Classified Ad Format feature only.
   *   
     */
    CLASSIFIED_AD_ONLY("ClassifiedAdOnly"),
  

    /**
     * 
   * The category supports the lead generation Motors Local Market feature only.
   *   
     */
    LOCAL_MARKET_BEST_OFFER_ONLY("LocalMarketBestOfferOnly"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   *   
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    AdFormatEnabledCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static AdFormatEnabledCodeType fromValue(String v) {
        if (v != null) {
            for (AdFormatEnabledCodeType c: AdFormatEnabledCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}