// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *         Contains the data for a user who is interested in bidding on items in a Live Auctions catalog.
 * 
 */
public class BidderDetailType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "UserID")
	@Order(value=0)
	public String userID;	
	
	@Element(name = "Email")
	@Order(value=1)
	public String email;	
	
	@Element(name = "FeedbackScore")
	@Order(value=2)
	public Integer feedbackScore;	
	
	@Element(name = "UniqueNegativeFeedbackCount")
	@Order(value=3)
	public Integer uniqueNegativeFeedbackCount;	
	
	@Element(name = "UniquePositiveFeedbackCount")
	@Order(value=4)
	public Integer uniquePositiveFeedbackCount;	
	
	@Element(name = "UniqueNeutralFeedbackCount")
	@Order(value=5)
	public Integer uniqueNeutralFeedbackCount;	
	
	@AnyElement
	@Order(value=6)
	public List<Object> any;	
	
    
}