// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * This enumerated type list the Feedback ratings that can be left by one eBay user for
 * another user regarding that user's experience with the another user during the
 * purchase/checkout flow of an order line item.
 * 
 */
public enum CommentTypeCodeType {

    /**
     * 
   * This value indicates that the submitting user's experience with the other user
   * (receiving feedback) was rated as a "Positive" experience. If an eBay user receives
   * a Positive rating for an order line item from a Verified User, their overall
   * Feedback score increases by a value of 1.
   * 
     */
    POSITIVE("Positive"),
  

    /**
     * 
   * This value indicates that the submitting user's experience with the other user
   * (receiving feedback) was rated as a "Neutral" experience. If an eBay user receives
   * a Neutral rating for an order line item from a Verified User, their overall
   * Feedback score remains the same.
   * 
     */
    NEUTRAL("Neutral"),
  

    /**
     * 
   * This value indicates that the submitting user's experience with the other user
   * (receiving feedback) was rated as a "Negative" experience. If an eBay user receives
   * a Negative rating for an order line item from a Verified User, their overall
   * Feedback score decreases by a value of 1.
   * 
     */
    NEGATIVE("Negative"),
  

    /**
     * 
   * This value indicates that a submitted Feedback entry was withdrawn. If a Feedback
   * entry is withdrawn, the effect of that entry on the overall Feedback score is
   * nullified. However, Feedback comments from the withdrawn entry are still visible.
   * 
     */
    WITHDRAWN("Withdrawn"),
  

    /**
     * 
   * This value indicates that a submitted Feedback entry was withdrawn based on the
   * decision of a third-party (such as eBay). If a Feedback
   * entry is withdrawn, the effect of that entry on the overall Feedback score is
   * nullified.
   * <br><br>
   * This value is only applicable to the eBay Motors site only.
   * 
     */
    INDEPENDENTLY_WITHDRAWN("IndependentlyWithdrawn"),
  

    /**
     * 
   * This value is reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    CommentTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static CommentTypeCodeType fromValue(String v) {
        if (v != null) {
            for (CommentTypeCodeType c: CommentTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}