// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * DayOfWeekCodeType - Specifies the day of week.
 * 
 */
public enum DayOfWeekCodeType {

    /**
     * 
   * Sunday
   * 
     */
    SUNDAY("Sunday"),
  

    /**
     * 
   * Monday
   * 
     */
    MONDAY("Monday"),
  

    /**
     * 
   * Tuesday
   * 
     */
    TUESDAY("Tuesday"),
  

    /**
     * 
   * Wednesday
   * 
     */
    WEDNESDAY("Wednesday"),
  

    /**
     * 
   * Thursday
   * 
     */
    THURSDAY("Thursday"),
  

    /**
     * 
   * Friday
   * 
     */
    FRIDAY("Friday"),
  

    /**
     * 
   * Saturday
   * 
     */
    SATURDAY("Saturday"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    DayOfWeekCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static DayOfWeekCodeType fromValue(String v) {
        if (v != null) {
            for (DayOfWeekCodeType c: DayOfWeekCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}