// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Ranges for use when offering insurance in combined payment orders.
 * 
 */
public enum FlatRateInsuranceRangeCodeType {

    /**
     * 
   * Range is 0.01 to 9.99
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_1("FlatRateInsuranceRange1"),
  

    /**
     * 
   * Range is 10.00 to 49.99
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_2("FlatRateInsuranceRange2"),
  

    /**
     * 
   * Range is 50.00 to 99.99
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_3("FlatRateInsuranceRange3"),
  

    /**
     * 
   * Range is 100.00 to 199.99
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_4("FlatRateInsuranceRange4"),
  

    /**
     * 
   * Range is 200.00 to 299.99
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_5("FlatRateInsuranceRange5"),
  

    /**
     * 
   * Range is 300.00 or greater
   * 
     */
    FLAT_RATE_INSURANCE_RANGE_6("FlatRateInsuranceRange6"),
  

    /**
     * 
   *  Reserved for internal or future use
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    FlatRateInsuranceRangeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static FlatRateInsuranceRangeCodeType fromValue(String v) {
        if (v != null) {
            for (FlatRateInsuranceRangeCodeType c: FlatRateInsuranceRangeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}