// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * <b>No longer recommended.</b> The eBay Store Cross Promotions are no longer
 * supported in the Trading API. Retrieves a list of upsell or cross-sell items associated
 * with the specified Item ID.
 * 
 */
@RootElement(name = "GetCrossPromotionsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetCrossPromotionsRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "PromotionMethod")
	@Order(value=1)
	public PromotionMethodCodeType promotionMethod;	
	
	@Element(name = "PromotionViewMode")
	@Order(value=2)
	public TradingRoleCodeType promotionViewMode;	
	
    
}