// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Returns summary and detail information about items the user is selling,
 * items scheduled to sell, currently listed, sold, and closed but not sold.
 * 
 */
@RootElement(name = "GetMyeBaySellingResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetMyeBaySellingResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "SellingSummary")
	@Order(value=0)
	public SellingSummaryType sellingSummary;	
	
	@Element(name = "ScheduledList")
	@Order(value=1)
	public PaginatedItemArrayType scheduledList;	
	
	@Element(name = "ActiveList")
	@Order(value=2)
	public PaginatedItemArrayType activeList;	
	
	@Element(name = "SoldList")
	@Order(value=3)
	public PaginatedOrderTransactionArrayType soldList;	
	
	@Element(name = "UnsoldList")
	@Order(value=4)
	public PaginatedItemArrayType unsoldList;	
	
	@Element(name = "Summary")
	@Order(value=5)
	public MyeBaySellingSummaryType summary;	
	
	@Element(name = "BidList")
	@Order(value=6)
	public PaginatedItemArrayType bidList;	
	
	@Element(name = "DeletedFromSoldList")
	@Order(value=7)
	public PaginatedOrderTransactionArrayType deletedFromSoldList;	
	
	@Element(name = "DeletedFromUnsoldList")
	@Order(value=8)
	public PaginatedItemArrayType deletedFromUnsoldList;	
	
    
}