// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Retrieves a list of the messages buyers have posted about your
 * active item listings.
 * 
 */
@RootElement(name = "GetMemberMessagesRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetMemberMessagesRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "MailMessageType")
	@Order(value=1)
	public MessageTypeCodeType mailMessageType;	
	
	@Element(name = "MessageStatus")
	@Order(value=2)
	public MessageStatusTypeCodeType messageStatus;	
	
	@Element(name = "DisplayToPublic")
	@Order(value=3)
	public Boolean displayToPublic;	
	
	@Element(name = "StartCreationTime")
	@Order(value=4)
	public Date startCreationTime;	
	
	@Element(name = "EndCreationTime")
	@Order(value=5)
	public Date endCreationTime;	
	
	@Element(name = "Pagination")
	@Order(value=6)
	public PaginationType pagination;	
	
	@Element(name = "MemberMessageID")
	@Order(value=7)
	public String memberMessageID;	
	
	@Element(name = "SenderID")
	@Order(value=8)
	public String senderID;	
	
    
}