// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *   Retrieves Selling Manager alerts.
 * This call is subject to change without notice; the deprecation process is
 * inapplicable to this call.
 * 
 */
@RootElement(name = "GetSellingManagerAlertsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSellingManagerAlertsRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}