// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

public enum InvocationStatusType {

    IN_PROGRESS("InProgress"),
  

    SUCCESS("Success"),
  

    FAILURE("Failure"),
  

    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    InvocationStatusType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static InvocationStatusType fromValue(String v) {
        if (v != null) {
            for (InvocationStatusType c: InvocationStatusType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}