// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Specifies the details of policy violations if the item was administratively canceled.
 * The details are the policy ID and the policy text.
 * 
 */
public class ItemPolicyViolationType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "PolicyID")
	@Order(value=0)
	public Long policyID;	
	
	@Element(name = "PolicyText")
	@Order(value=1)
	public String policyText;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
    
}