// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains the IDs for the Listing Designer theme and template (if either are
 * used) associated with an item, which can optionally be used to enhance the
 * appearance of the item's description. Cannot be used with Photo Display.
 * 
 */
public class ListingDesignerType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "LayoutID")
	@Order(value=0)
	public Integer layoutID;	
	
	@Element(name = "OptimalPictureSize")
	@Order(value=1)
	public Boolean optimalPictureSize;	
	
	@Element(name = "ThemeID")
	@Order(value=2)
	public Integer themeID;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}