// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * A list of one or more ModifyName containers. Each ModifyName container has Name and NewName elements.
 * 
 */
public class ModifyNameArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ModifyName")
	@Order(value=0)
	public List<ModifyNameType> modifyName;	
	
    
}