// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 *       Indicates success or failure of the attempt to revise the listing's checkout status.
 * 
 */
@RootElement(name = "ReviseCheckoutStatusResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ReviseCheckoutStatusResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}