// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

/**
 * 
 * Indicates the filters for Selling Manager sold listings.
 * 
 */
public enum SellingManagerSoldListingsPropertyTypeCodeType {

    /**
     * 
   * Item is not paid and not shipped.
   * 
     */
    NOT_PAID_NOT_SHIPPED("NotPaidNotShipped"),
  

    /**
     * 
   * Item is paid but not shipped.
   * 
     */
    PAID_NOT_SHIPPED("PaidNotShipped"),
  

    /**
     * 
   * Item is paid but not shipped.
   * 
     */
    PRINT_SHIPPING_LABEL("PrintShippingLabel"),
  

    /**
     * 
   * Item is paid for and is shipped.
   * 
     */
    PAID_SHIPPED("PaidShipped"),
  

    /**
     * 
   * An alert has been issued about a listing that is paid with no feedback left.
   * 
     */
    PAID_NO_FEEDBACK("PaidNoFeedback"),
  

    /**
     * 
   * Payment Reminder emails not sent due to system error.
   * 
     */
    PAYMENT_REMINDER_SEND_ERROR("PaymentReminderSendError"),
  

    /**
     * 
   * Payment received notification not sent due to system error.
   * 
     */
    PAYMENT_RECEIVED_NOTIFICATION_SEND_ERROR("PaymentReceivedNotificationSendError"),
  

    /**
     * 
   * Request shipping address emails not sent due to system error.
   * 
     */
    REQUEST_FOR_SHIPPING_ADDRESS_SEND_ERROR("RequestForShippingAddressSendError"),
  

    /**
     * 
   * Request shipping address emails not sent due to system error.
   * 
     */
    SHIPPING_NOTIFICATION_SEND_ERROR("ShippingNotificationSendError"),
  

    /**
     * 
   * Personalized emails not sent due to system error.
   * 
     */
    PERSONALIZED_EMAILS_SEND_ERROR("PersonalizedEmailsSendError"),
  

    /**
     * 
   * Winning Buyer Notification not sent due to system error.
   * 
     */
    WINNING_BUYER_NOTIFICATION_SEND_ERROR("WinningBuyerNotificationSendError"),
  

    /**
     * 
   * Final value fee credit requests can be filed.
   * 
     */
    FEE_CREDIT_REQUEST("FeeCreditRequest"),
  

    /**
     * 
   * If true, indicates that the PayPal Payment Received alert has been issued.
   * 
     */
    PAY_PAL_PAYMENT("PayPalPayment"),
  

    /**
     * 
   * Automated feedback message is not sent.
   * 
     */
    FEEDBACK_MESSAGE_NOT_SENT("FeedbackMessageNotSent"),
  

    /**
     * 
   * Feedback Reminder emails not sent due to system error.
   * 
     */
    FEEDBACK_REMINDER_SEND_ERROR("FeedbackReminderSendError"),
  

    /**
     * 
   * Item is not shipped.
   * 
     */
    NOT_SHIPPED("NotShipped"),
  

    /**
     * 
   * Listing eligible for unpaid item reminder
   * 
     */
    UNPAID_ITEM_REMINDER("UnpaidItemReminder"),
  

    /**
     * 
   * Escrow status is Cancelled.
   * 
     */
    ESCROW_CANCELLED("EscrowCancelled"),
  

    /**
     * 
   * Escrow status is Completed.
   * 
     */
    ESCROW_COMPLETED("EscrowCompleted"),
  

    /**
     * 
   * Escrow status is Initiated.
   * 
     */
    ESCROW_INITIATED("EscrowInitiated"),
  

    /**
     * 
   * Escrow status is in refund state.
   * 
     */
    ESCROW_MANAGE_REFUND("EscrowManageRefund"),
  

    /**
     * 
   * Item is shipped and Escrow status is in Release payment.
   * 
     */
    ESCROW_RELEASE_PAYMENT("EscrowReleasePayment"),
  

    /**
     * 
   * Payment is confirmed and item can be shipped to buyer.
   * 
     */
    ESCROW_SHIP_TO_BUYER("EscrowShipToBuyer"),
  

    /**
     * 
   * All Escrow states.
   * 
     */
    ESCROW_SOLD_ALL("EscrowSoldAll"),
  

    /**
     * 
   * Item is shipped and feedback is not yet received.
   * 
     */
    SHIPPED_AND_AWAITING_FEEDBACK("ShippedAndAwaitingFeedback"),
  

    /**
     * 
   * New international sale.
   * 
     */
    INTERNATIONAL_SALE("InternationalSale"),
  

    /**
     * 
   * Charity filter.
   * 
     */
    E_BAY_GIVING_WORKS_DONATION_OWED("eBayGivingWorksDonationOwed"),
  

    /**
     * 
   * Payment is overdue.
   * 
     */
    PAYMENT_OVER_DUE("PaymentOverDue"),
  

    /**
     * 
   * Payment is done with PaisaPay Escrow.
   * 
     */
    PADI_WITH_PAISA_PAY_ESCROW("PadiWithPaisaPayEscrow"),
  

    /**
     * 
   * Failed to send custom email template 1.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_1_SEND_ERROR("CustomEmailTemplate1SendError"),
  

    /**
     * 
   * Failed to send custom email template 2.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_2_SEND_ERROR("CustomEmailTemplate2SendError"),
  

    /**
     * 
   * Failed to send custom email template 3.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_3_SEND_ERROR("CustomEmailTemplate3SendError"),
  

    /**
     * 
   * Failed to send custom email template 4.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_4_SEND_ERROR("CustomEmailTemplate4SendError"),
  

    /**
     * 
   * Failed to send custom email template 5.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_5_SEND_ERROR("CustomEmailTemplate5SendError"),
  

    /**
     * 
   * Failed to send custom email template 6.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_6_SEND_ERROR("CustomEmailTemplate6SendError"),
  

    /**
     * 
   * Failed to send custom email template 7.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_7_SEND_ERROR("CustomEmailTemplate7SendError"),
  

    /**
     * 
   * Failed to send custom email template 8.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_8_SEND_ERROR("CustomEmailTemplate8SendError"),
  

    /**
     * 
   * Failed to send custom email template 9.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_9_SEND_ERROR("CustomEmailTemplate9SendError"),
  

    /**
     * 
   * Failed to send custom email template 10.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_10_SEND_ERROR("CustomEmailTemplate10SendError"),
  

    /**
     * 
   * Failed to send custom email template 11.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_11_SEND_ERROR("CustomEmailTemplate11SendError"),
  

    /**
     * 
   * Failed to send custom email template 12.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_12_SEND_ERROR("CustomEmailTemplate12SendError"),
  

    /**
     * 
   * Failed to send custom email template 13.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_13_SEND_ERROR("CustomEmailTemplate13SendError"),
  

    /**
     * 
   * Failed to send custom email template 14.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_14_SEND_ERROR("CustomEmailTemplate14SendError"),
  

    /**
     * 
   * Failed to send custom email template 15.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_15_SEND_ERROR("CustomEmailTemplate15SendError"),
  

    /**
     * 
   * Failed to send custom email template 16.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_16_SEND_ERROR("CustomEmailTemplate16SendError"),
  

    /**
     * 
   * Failed to send custom email template 17.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_17_SEND_ERROR("CustomEmailTemplate17SendError"),
  

    /**
     * 
   * Failed to send custom email template 18.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_18_SEND_ERROR("CustomEmailTemplate18SendError"),
  

    /**
     * 
   * Failed to send custom email template 19.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_19_SEND_ERROR("CustomEmailTemplate19SendError"),
  

    /**
     * 
   * Failed to send custom email template 20.
   * 
     */
    CUSTOM_EMAIL_TEMPLATE_20_SEND_ERROR("CustomEmailTemplate20SendError"),
  

    /**
     * 
   * Reserved for future use. If a buyer requests to return an item, the seller's response is required.
   * 
     */
    RESPONSE_REQUIRED_FOR_RETURN_CASE("ResponseRequiredForReturnCase"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    SellingManagerSoldListingsPropertyTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static SellingManagerSoldListingsPropertyTypeCodeType fromValue(String v) {
        if (v != null) {
            for (SellingManagerSoldListingsPropertyTypeCodeType c: SellingManagerSoldListingsPropertyTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}