// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Describes a Selling Manager Product
 */
public class SellingManagerProductType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "SellingManagerProductDetails")
	@Order(value=0)
	public SellingManagerProductDetailsType sellingManagerProductDetails;	
	
	@Element(name = "SellingManagerTemplateDetailsArray")
	@Order(value=1)
	public SellingManagerTemplateDetailsArrayType sellingManagerTemplateDetailsArray;	
	
	@Element(name = "SellingManagerProductInventoryStatus")
	@Order(value=2)
	public SellingManagerProductInventoryStatusType sellingManagerProductInventoryStatus;	
	
	@Element(name = "SellingManagerProductSpecifics")
	@Order(value=3)
	public SellingManagerProductSpecificsType sellingManagerProductSpecifics;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}