// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type defining the <b>SellerRatingSummaryArray</b> container that is returned
 * in the <b>GetFeedback</b> response. The <b>SellerRatingSummaryArray</b>
 * container consists of an array of <b>AverageRatingSummary</b> containers,
 * which provide details on Detailed Seller Ratings (DSRs), including the type of rating
 * (Communication, Item As Described, Shipping and Handling Charges, or Shipping Time), the
 * seller's average rating for that DSR type, the total number of DSR ratings, and the
 * period in which those ratings were received (the last year or the last 30 days).
 * 
 */
public class SellerRatingSummaryArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AverageRatingSummary")
	@Order(value=0)
	public List<AverageRatingSummaryType> averageRatingSummary;	
	
    
}