// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type defining the Alert container, which contains summary information on one type of
 * Selling Manager alert.
 * 
 */
public class SellingManagerAlertType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AlertType")
	@Order(value=0)
	public SellingManagerAlertTypeCodeType alertType;	
	
	@Element(name = "SoldAlert")
	@Order(value=1)
	public SellingManagerSoldListingsPropertyTypeCodeType soldAlert;	
	
	@Element(name = "InventoryAlert")
	@Order(value=2)
	public SellingManagerInventoryPropertyTypeCodeType inventoryAlert;	
	
	@Element(name = "AutomationAlert")
	@Order(value=3)
	public SellingManagerAutomationPropertyTypeCodeType automationAlert;	
	
	@Element(name = "PaisaPayAlert")
	@Order(value=4)
	public SellingManagerPaisaPayPropertyTypeCodeType paisaPayAlert;	
	
	@Element(name = "GeneralAlert")
	@Order(value=5)
	public SellingManagerGeneralPropertyTypeCodeType generalAlert;	
	
	@Element(name = "DurationInDays")
	@Order(value=6)
	public Integer durationInDays;	
	
	@Element(name = "Count")
	@Order(value=7)
	public Long count;	
	
	@AnyElement
	@Order(value=8)
	public List<Object> any;	
	
    
}