// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.trading.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

public class ValType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ValueLiteral")
	@Order(value=0)
	public String valueLiteral;	
	
	@Element(name = "SuggestedValueLiteral")
	@Order(value=1)
	public List<String> suggestedValueLiteral;	
	
	@Element(name = "ValueID")
	@Order(value=2)
	public Integer valueID;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}