// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap11;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import javax.xml.namespace.QName;

/**
 * 
 *     Fault reporting structure
 *   
 */
@RootElement(name = "Fault", namespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class Fault implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	public QName faultcode;	
	
	@Element
	public String faultstring;	
	
	@Element
	public String faultactor;	
	
	@Element
	public Detail detail;	
	
    
}