// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.finding.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This is the base class container for all service operation requests.
 * 
 */
public abstract class BaseServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

    
}