// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.finding.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains details about a category.
 * 
 */
public class Category implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public String categoryId;	
	
	@Element
	@Order(value=1)
	public String categoryName;	
	
    
}