// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.finding.api;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Defines the image URL returned in galleryInfoContainer.
 * 
 */
public class GalleryURL implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	@Order(value=0)
	public String value;	
	
	@Attribute  
	@Order(value=1)
	public GallerySizeEnum gallerySize;	
	
    
}