// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.amazon.webservices.awsecommerceservice._2011_08_01;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "VariationSummary", namespace = "http://webservices.amazon.com/AWSECommerceService/2011-08-01")
public class VariationSummary implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "LowestPrice")
	@Order(value=0)
	public Price lowestPrice;	
	
	@Element(name = "HighestPrice")
	@Order(value=1)
	public Price highestPrice;	
	
	@Element(name = "LowestSalePrice")
	@Order(value=2)
	public Price lowestSalePrice;	
	
	@Element(name = "HighestSalePrice")
	@Order(value=3)
	public Price highestSalePrice;	
	
    
}