// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap12;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import javax.xml.namespace.QName;

@RootElement(name = "NotUnderstood", namespace = "http://www.w3.org/2003/05/soap-envelope")
public class NotUnderstoodType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Attribute  
	public QName qname;	
	
    
}