// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.nano.soap12;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class Reasontext implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	public String value;	
	
	@Attribute  
	public String lang;	
	
    
}