// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * Enumerated type that indicates whether or not a nonprofit charity organization is
 * registered with eBay Giving Works. See the <a href="http://pages.ebay.com/help/sell/nonprofit.html#certify">Certifying your organization with MissionFish</a>
 * help topic for more information on registering with MissionFish and the benefits that come
 * with being a registered eBay Giving Works organization.
 * 
 */
public enum AddressTypeCodeType {

    /**
     * 
   * This value indicates that the address contained in the <b>NonProfitAddress</b>
   * container is for a non-registered charity organization.
   * 
     */
    CONTACT("Contact"),
  

    /**
     * 
   * This value indicates that the address contained in the <b>NonProfitAddress</b>
   * container is for a charity organization registered with eBay Giving Works.
   * 
     */
    REGISTERED("Registered"),
  

    /**
     * 
   * This value is reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    AddressTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static AddressTypeCodeType fromValue(String v) {
        if (v != null) {
            for (AddressTypeCodeType c: AddressTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}