// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * AddSecondChanceItem response for a new Second Chance Offer listing.
 * 
 */
@RootElement(name = "AddSecondChanceItemResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class AddSecondChanceItemResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "StartTime")
	@Order(value=1)
	public Date startTime;	
	
	@Element(name = "EndTime")
	@Order(value=2)
	public Date endTime;	
	
    
}