// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * This type is deprecated as the Bid Assistant feature is no longer available.
 * 
 * 
 */
public class BidGroupType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "BidGroupItem")
	@Order(value=0)
	public List<BidGroupItemType> bidGroupItem;	
	
	@Element(name = "BidGroupID")
	@Order(value=1)
	public Long bidGroupID;	
	
	@Element(name = "BidGroupName")
	@Order(value=2)
	public String bidGroupName;	
	
	@Element(name = "BidGroupStatus")
	@Order(value=3)
	public BidGroupStatusCodeType bidGroupStatus;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}