// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * This type is deprecated as the Bid Assistant feature is no longer available.
 *  
 * 
 */
public enum BidGroupItemStatusCodeType {

    /**
     * 
   * 
   * (out) The items in the group currently being bid on.
   * 
     */
    CURRENT_BID("CurrentBid"),
  

    /**
     * 
   * 
   * (out) Items in the group that were not bid on because a user retracted a bid
   * and closed his group or because eBay Customer Support ended a group and all
   * the active and pending items within that group were cancelled.
   * 
     */
    CANCELLED("Cancelled"),
  

    /**
     * 
   * 
   * (out) Items in the bid group that are currently active, but have not yet been
   * bid on.
   * 
     */
    PENDING("Pending"),
  

    /**
     * 
   * 
   * (out) Items that have been skipped and not bid on (and bidded has ended).
   * 
     */
    SKIPPED("Skipped"),
  

    /**
     * 
   * 
   * (out) Item has ended.
   * 
     */
    ENDED("Ended"),
  

    /**
     * 
   * 
   * (out) Item was purchased and has ended.
   * 
     */
    WON("Won"),
  

    /**
     * 
   * 
   * (out) Item has ended.
   * 
     */
    GROUP_CLOSED("GroupClosed"),
  

    /**
     * 
   * 
   * Reserved for future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    BidGroupItemStatusCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static BidGroupItemStatusCodeType fromValue(String v) {
        if (v != null) {
            for (BidGroupItemStatusCodeType c: BidGroupItemStatusCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}