// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Returns the status of delete folder operation.
 * 
 */
@RootElement(name = "DeleteSellingManagerInventoryFolderResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class DeleteSellingManagerInventoryFolderResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}