// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Contains all information describing a dispute.
 * 
 */
public class DisputeType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DisputeID")
	@Order(value=0)
	public String disputeID;	
	
	@Element(name = "DisputeRecordType")
	@Order(value=1)
	public DisputeRecordTypeCodeType disputeRecordType;	
	
	@Element(name = "DisputeState")
	@Order(value=2)
	public DisputeStateCodeType disputeState;	
	
	@Element(name = "DisputeStatus")
	@Order(value=3)
	public DisputeStatusCodeType disputeStatus;	
	
	@Element(name = "OtherPartyRole")
	@Order(value=4)
	public TradingRoleCodeType otherPartyRole;	
	
	@Element(name = "OtherPartyName")
	@Order(value=5)
	public String otherPartyName;	
	
	@Element(name = "UserRole")
	@Order(value=6)
	public TradingRoleCodeType userRole;	
	
	@Element(name = "BuyerUserID")
	@Order(value=7)
	public String buyerUserID;	
	
	@Element(name = "SellerUserID")
	@Order(value=8)
	public String sellerUserID;	
	
	@Element(name = "TransactionID")
	@Order(value=9)
	public String transactionID;	
	
	@Element(name = "Item")
	@Order(value=10)
	public ItemType item;	
	
	@Element(name = "DisputeReason")
	@Order(value=11)
	public DisputeReasonCodeType disputeReason;	
	
	@Element(name = "DisputeExplanation")
	@Order(value=12)
	public DisputeExplanationCodeType disputeExplanation;	
	
	@Element(name = "DisputeCreditEligibility")
	@Order(value=13)
	public DisputeCreditEligibilityCodeType disputeCreditEligibility;	
	
	@Element(name = "DisputeCreatedTime")
	@Order(value=14)
	public Date disputeCreatedTime;	
	
	@Element(name = "DisputeModifiedTime")
	@Order(value=15)
	public Date disputeModifiedTime;	
	
	@Element(name = "DisputeResolution")
	@Order(value=16)
	public List<DisputeResolutionType> disputeResolution;	
	
	@Element(name = "DisputeMessage")
	@Order(value=17)
	public List<DisputeMessageType> disputeMessage;	
	
	@Element(name = "Escalation")
	@Order(value=18)
	public Boolean escalation;	
	
	@Element(name = "PurchaseProtection")
	@Order(value=19)
	public Boolean purchaseProtection;	
	
	@Element(name = "OrderLineItemID")
	@Order(value=20)
	public String orderLineItemID;	
	
	@AnyElement
	@Order(value=21)
	public List<Object> any;	
	
    
}