// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Indicates whether the category supports the use of a company name
 * when contacting the seller about Classified Ad format listings.
 * Added for EbayMotors Pro users.
 * 
 */
public class EBayMotorsProCompanyNameEnabledDefinitionType implements Serializable {

    private static final long serialVersionUID = -1L;

	@AnyElement
	@Order(value=0)
	public List<Object> any;	
	
    
}