// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * Specifies the seller's reason for ending an item listing early. This
 * is required if the seller ended the listing early and the item did
 * not successfully sell of if the item has bids and the seller wants to sell
 * to the high bidder.
 * 
 */
public enum EndReasonCodeType {

    /**
     * 
   * The item was lost or broken.
   * 
     */
    LOST_OR_BROKEN("LostOrBroken"),
  

    /**
     * 
   * The item is no longer available for sale.
   * 
     */
    NOT_AVAILABLE("NotAvailable"),
  

    /**
     * 
   * The start price or reserve price is incorrect.
   * 
     */
    INCORRECT("Incorrect"),
  

    /**
     * 
   * The listing contained an error (other than start price or reserve
   * price).
   * 
     */
    OTHER_LISTING_ERROR("OtherListingError"),
  

    /**
     * 
   * Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode"),
  

    /**
     * 
   *   The listing has qualifying bids (i.e., there is a current high bid that,
   *   when applicable, meets the minimum reserve price) and there are more
   *   than 12 hours before the listing ends.
   *   Sell the item to the highest eligible bidder.
   *   <br>
   *   In the last 12 hours of an item listing, you cannot end an item early
   *   if it has bids.
   * 
     */
    SELL_TO_HIGH_BIDDER("SellToHighBidder"),
  

    /**
     * 
   * The vehicle was sold. Applies to local classified listings for vehicles only.
   * 
     */
    SOLD("Sold");
  
  
    private final String value;
  
    EndReasonCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static EndReasonCodeType fromValue(String v) {
        if (v != null) {
            for (EndReasonCodeType c: EndReasonCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}