// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * This type is deprecated as the call is no longer available.
 * 
 */
public class ExtendedProductFinderIDType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ProductFinderID")
	@Order(value=0)
	public Integer productFinderID;	
	
	@Element(name = "ProductFinderBuySide")
	@Order(value=1)
	public Boolean productFinderBuySide;	
	
    
}