// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Includes the authentication token for the user and the date it expires.
 * 
 */
@RootElement(name = "FetchTokenResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class FetchTokenResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public String eBayAuthToken;	
	
	@Element(name = "HardExpirationTime")
	@Order(value=1)
	public Date hardExpirationTime;	
	
	@Element(name = "RESTToken")
	@Order(value=2)
	public String restToken;	
	
    
}