// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Retrieves a map of old category IDs and corresponding active
 * category IDs defined for the site to which the request is sent.
 * 
 */
@RootElement(name = "GetCategoryMappingsRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetCategoryMappingsRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CategoryVersion")
	@Order(value=0)
	public String categoryVersion;	
	
    
}