// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * 
 * Contains the category data for the eBay site specified as input. The category
 * data is contained in a CategoryArrayType object, within which are zero, one, or
 * multiple CategoryType objects. Each CategoryType object contains the detail data
 * for one category. Other fields tell how many categories are returned in a call,
 * when the category hierarchy was last updated, and the version of the category
 * hierarchy (all three of which can differ from one eBay site to the next).
 * 
 */
@RootElement(name = "GetCategoriesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetCategoriesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CategoryArray")
	@Order(value=0)
	public CategoryArrayType categoryArray;	
	
	@Element(name = "CategoryCount")
	@Order(value=1)
	public Integer categoryCount;	
	
	@Element(name = "UpdateTime")
	@Order(value=2)
	public Date updateTime;	
	
	@Element(name = "CategoryVersion")
	@Order(value=3)
	public String categoryVersion;	
	
	@Element(name = "ReservePriceAllowed")
	@Order(value=4)
	public Boolean reservePriceAllowed;	
	
	@Element(name = "MinimumReservePrice")
	@Order(value=5)
	public Double minimumReservePrice;	
	
	@Element(name = "ReduceReserveAllowed")
	@Order(value=6)
	public Boolean reduceReserveAllowed;	
	
    
}