// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Details about a specified site in response to <b>GeteBayDetailsRequest</b>.
 * If no <b>DetailName</b>
 * field is identified in the request, all elements of <b>GeteBayDetailsResponse</b> are
 * returned. Otherwise, eBay returns only the elements corresponding to the specified
 * <b>DetailName</b> fields. <b>UpdateTime</b> gives the time of modification of the most recently
 * modified <b>DetailName</b>.
 * 
 */
@RootElement(name = "GeteBayDetailsResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GeteBayDetailsResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CountryDetails")
	@Order(value=0)
	public List<CountryDetailsType> countryDetails;	
	
	@Element(name = "CurrencyDetails")
	@Order(value=1)
	public List<CurrencyDetailsType> currencyDetails;	
	
	@Element(name = "DispatchTimeMaxDetails")
	@Order(value=2)
	public List<DispatchTimeMaxDetailsType> dispatchTimeMaxDetails;	
	
	@Element(name = "PaymentOptionDetails")
	@Order(value=3)
	public List<PaymentOptionDetailsType> paymentOptionDetails;	
	
	@Element(name = "RegionDetails")
	@Order(value=4)
	public List<RegionDetailsType> regionDetails;	
	
	@Element(name = "ShippingLocationDetails")
	@Order(value=5)
	public List<ShippingLocationDetailsType> shippingLocationDetails;	
	
	@Element(name = "ShippingServiceDetails")
	@Order(value=6)
	public List<ShippingServiceDetailsType> shippingServiceDetails;	
	
	@Element(name = "SiteDetails")
	@Order(value=7)
	public List<SiteDetailsType> siteDetails;	
	
	@Element(name = "TaxJurisdiction")
	@Order(value=8)
	public List<TaxJurisdictionType> taxJurisdiction;	
	
	@Element(name = "URLDetails")
	@Order(value=9)
	public List<URLDetailsType> urlDetails;	
	
	@Element(name = "TimeZoneDetails")
	@Order(value=10)
	public List<TimeZoneDetailsType> timeZoneDetails;	
	
	@Element(name = "ItemSpecificDetails")
	@Order(value=11)
	public List<ItemSpecificDetailsType> itemSpecificDetails;	
	
	@Element(name = "UnitOfMeasurementDetails")
	@Order(value=12)
	public List<UnitOfMeasurementDetailsType> unitOfMeasurementDetails;	
	
	@Element(name = "RegionOfOriginDetails")
	@Order(value=13)
	public List<RegionOfOriginDetailsType> regionOfOriginDetails;	
	
	@Element(name = "ShippingPackageDetails")
	@Order(value=14)
	public List<ShippingPackageDetailsType> shippingPackageDetails;	
	
	@Element(name = "ShippingCarrierDetails")
	@Order(value=15)
	public List<ShippingCarrierDetailsType> shippingCarrierDetails;	
	
	@Element(name = "ReturnPolicyDetails")
	@Order(value=16)
	public ReturnPolicyDetailsType returnPolicyDetails;	
	
	@Element(name = "ListingStartPriceDetails")
	@Order(value=17)
	public List<ListingStartPriceDetailsType> listingStartPriceDetails;	
	
	@Element(name = "BuyerRequirementDetails")
	@Order(value=18)
	public List<SiteBuyerRequirementDetailsType> buyerRequirementDetails;	
	
	@Element(name = "ListingFeatureDetails")
	@Order(value=19)
	public List<ListingFeatureDetailsType> listingFeatureDetails;	
	
	@Element(name = "VariationDetails")
	@Order(value=20)
	public VariationDetailsType variationDetails;	
	
	@Element(name = "ExcludeShippingLocationDetails")
	@Order(value=21)
	public List<ExcludeShippingLocationDetailsType> excludeShippingLocationDetails;	
	
	@Element(name = "UpdateTime")
	@Order(value=22)
	public Date updateTime;	
	
	@Element(name = "RecoupmentPolicyDetails")
	@Order(value=23)
	public List<RecoupmentPolicyDetailsType> recoupmentPolicyDetails;	
	
	@Element(name = "ShippingCategoryDetails")
	@Order(value=24)
	public List<ShippingCategoryDetailsType> shippingCategoryDetails;	
	
    
}