// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Response to GetItemsAwaitingFeedback.
 * 
 */
@RootElement(name = "GetItemsAwaitingFeedbackResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetItemsAwaitingFeedbackResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemsAwaitingFeedback")
	@Order(value=0)
	public PaginatedTransactionArrayType itemsAwaitingFeedback;	
	
    
}