// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * This type is deprecated as the call is no longer available.
 * 
 * 
 */
@RootElement(name = "GetProductSearchPageRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetProductSearchPageRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "AttributeSystemVersion")
	@Order(value=0)
	public String attributeSystemVersion;	
	
	@Element(name = "AttributeSetID")
	@Order(value=1)
	public List<Integer> attributeSetID;	
	
    
}