// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Returns recommended changes or opportunities for improvement
 * related to listing data that was passed in a GetItemRecommendations request.
 * 
 */
public class GetRecommendationsResponseContainerType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ListingAnalyzerRecommendations")
	@Order(value=0)
	public ListingAnalyzerRecommendationsType listingAnalyzerRecommendations;	
	
	@Element(name = "SIFFTASRecommendations")
	@Order(value=1)
	public SIFFTASRecommendationsType sifftasRecommendations;	
	
	@Element(name = "PricingRecommendations")
	@Order(value=2)
	public PricingRecommendationsType pricingRecommendations;	
	
	@Element(name = "AttributeRecommendations")
	@Order(value=3)
	public AttributeRecommendationsType attributeRecommendations;	
	
	@Element(name = "ProductRecommendations")
	@Order(value=4)
	public ProductRecommendationsType productRecommendations;	
	
	@Element(name = "CorrelationID")
	@Order(value=5)
	public String correlationID;	
	
	@Element(name = "Recommendations")
	@Order(value=6)
	public RecommendationsType recommendations;	
	
	@Element(name = "ProductListingDetails")
	@Order(value=7)
	public ProductListingDetailsType productListingDetails;	
	
	@Element(name = "Title")
	@Order(value=8)
	public String title;	
	
	@AnyElement
	@Order(value=9)
	public List<Object> any;	
	
    
}