// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Returns the shipping discount profiles defined by the user, along with other combined
 * payment-related details such as packaging and handling costs.
 * 
 */
@RootElement(name = "GetShippingDiscountProfilesRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetShippingDiscountProfilesRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}