// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Retrieves a brief summary of the requester's status as an eBay seller.
 * 
 */
@RootElement(name = "GetSellerDashboardRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetSellerDashboardRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

    
}