// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the Store preferences retrieved for a user.
 * 
 */
@RootElement(name = "GetStorePreferencesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetStorePreferencesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "StorePreferences")
	@Order(value=0)
	public StorePreferencesType storePreferences;	
	
    
}