// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains some or all of the authenticated user's preferences. The preferences are
 * grouped in sets and are returned according to the flag settings in the request.
 * 
 */
@RootElement(name = "GetUserPreferencesResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetUserPreferencesResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "BidderNoticePreferences")
	@Order(value=0)
	public BidderNoticePreferencesType bidderNoticePreferences;	
	
	@Element(name = "CombinedPaymentPreferences")
	@Order(value=1)
	public CombinedPaymentPreferencesType combinedPaymentPreferences;	
	
	@Element(name = "CrossPromotionPreferences")
	@Order(value=2)
	public CrossPromotionPreferencesType crossPromotionPreferences;	
	
	@Element(name = "SellerPaymentPreferences")
	@Order(value=3)
	public SellerPaymentPreferencesType sellerPaymentPreferences;	
	
	@Element(name = "SellerFavoriteItemPreferences")
	@Order(value=4)
	public SellerFavoriteItemPreferencesType sellerFavoriteItemPreferences;	
	
	@Element(name = "EndOfAuctionEmailPreferences")
	@Order(value=5)
	public EndOfAuctionEmailPreferencesType endOfAuctionEmailPreferences;	
	
	@Element(name = "EmailShipmentTrackingNumberPreference")
	@Order(value=6)
	public Boolean emailShipmentTrackingNumberPreference;	
	
	@Element(name = "RequiredShipPhoneNumberPreference")
	@Order(value=7)
	public Boolean requiredShipPhoneNumberPreference;	
	
	@Element(name = "ProStoresPreference")
	@Order(value=8)
	public ProStoresCheckoutPreferenceType proStoresPreference;	
	
	@Element(name = "UnpaidItemAssistancePreferences")
	@Order(value=9)
	public UnpaidItemAssistancePreferencesType unpaidItemAssistancePreferences;	
	
	@Element(name = "SellerExcludeShipToLocationPreferences")
	@Order(value=10)
	public SellerExcludeShipToLocationPreferencesType sellerExcludeShipToLocationPreferences;	
	
	@Element(name = "PurchaseReminderEmailPreferences")
	@Order(value=11)
	public PurchaseReminderEmailPreferencesType purchaseReminderEmailPreferences;	
	
	@Element(name = "SellerThirdPartyCheckoutDisabled")
	@Order(value=12)
	public Boolean sellerThirdPartyCheckoutDisabled;	
	
	@Element(name = "SellerProfilePreferences")
	@Order(value=13)
	public SellerProfilePreferencesType sellerProfilePreferences;	
	
	@Element(name = "SellerReturnPreferences")
	@Order(value=14)
	public SellerReturnPreferencesType sellerReturnPreferences;	
	
	@Element(name = "OfferGlobalShippingProgramPreference")
	@Order(value=15)
	public Boolean offerGlobalShippingProgramPreference;	
	
	@Element(name = "DispatchCutoffTimePreference")
	@Order(value=16)
	public DispatchCutoffTimePreferencesType dispatchCutoffTimePreference;	
	
    
}