// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Contains the Want It Now post data returned by the call. The data for the
 * specified post listing is returned in a WantItNowPostType object.
 *  
 */
@RootElement(name = "GetWantItNowPostResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class GetWantItNowPostResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "WantItNowPost")
	@Order(value=0)
	public WantItNowPostType wantItNowPost;	
	
    
}