// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Details about custom Item Specifics validation rules.
 * 
 */
public class ItemSpecificDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "MaxItemSpecificsPerItem")
	@Order(value=0)
	public Integer maxItemSpecificsPerItem;	
	
	@Element(name = "MaxValuesPerName")
	@Order(value=1)
	public Integer maxValuesPerName;	
	
	@Element(name = "MaxCharactersPerValue")
	@Order(value=2)
	public Integer maxCharactersPerValue;	
	
	@Element(name = "MaxCharactersPerName")
	@Order(value=3)
	public Integer maxCharactersPerName;	
	
	@Element(name = "DetailVersion")
	@Order(value=4)
	public String detailVersion;	
	
	@Element(name = "UpdateTime")
	@Order(value=5)
	public Date updateTime;	
	
	@AnyElement
	@Order(value=6)
	public List<Object> any;	
	
    
}