// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * (out) Identifies the item field that the tip relates to.
 * 
 */
public class ListingTipFieldType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ListingTipFieldID")
	@Order(value=0)
	public String listingTipFieldID;	
	
	@Element(name = "FieldTip")
	@Order(value=1)
	public String fieldTip;	
	
	@Element(name = "CurrentFieldText")
	@Order(value=2)
	public String currentFieldText;	
	
	@Element(name = "CurrentFieldValue")
	@Order(value=3)
	public String currentFieldValue;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}