// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * ListingFlowCodeType - Type declaration to be used by other schema.
 * Identifies the listing flows on the eBay Web site for use with calls like
 * GetItemRecommendations.
 * 
 */
public enum ListingFlowCodeType {

    /**
     * 
   * (in) AddItem (Sell Your Item) listing flow.
   * 
     */
    ADD_ITEM("AddItem"),
  

    /**
     * 
   * (in) ReviseItem (Revise Your Item) listing flow.
   * 
     */
    REVISE_ITEM("ReviseItem"),
  

    /**
     * 
   * (in) RelistItem listing flow.
   * 
     */
    RELIST_ITEM("RelistItem"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    ListingFlowCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ListingFlowCodeType fromValue(String v) {
        if (v != null) {
            for (ListingFlowCodeType c: ListingFlowCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}