// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Type defining the <b>ListingStartPriceDetails</b> container returned in
 * <b>GeteBayDetails</b>. The <b>ListingStartPriceDetails</b>
 * container lists the minimum start price for auction listings, the minimum sale price
 * for fixed-price listings, and the minimum percentage value that a Buy It Now price for
 * an auction listing must be above the minimum start price for that same listing.
 * <br><br>
 * The <b>ListingStartPriceDetails</b> container is returned if
 * <b>ListingStartPriceDetails</b> is included as a <b>DetailName</b>
 * filter in the request, or if no lt;b>DetailName</b> filters are used in the request.
 * 
 */
public class ListingStartPriceDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Description")
	@Order(value=0)
	public String description;	
	
	@Element(name = "ListingType")
	@Order(value=1)
	public ListingTypeCodeType listingType;	
	
	@Element(name = "StartPrice")
	@Order(value=2)
	public AmountType startPrice;	
	
	@Element(name = "DetailVersion")
	@Order(value=3)
	public String detailVersion;	
	
	@Element(name = "UpdateTime")
	@Order(value=4)
	public Date updateTime;	
	
	@Element(name = "MinBuyItNowPricePercent")
	@Order(value=5)
	public Float minBuyItNowPricePercent;	
	
	@AnyElement
	@Order(value=6)
	public List<Object> any;	
	
    
}