// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Details of a buyer's maximum unpaid item strikes in a pre-defined time period. This is applicable only to sellers.
 */
public class MaximumUnpaidItemStrikesInfoDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "MaximumUnpaidItemStrikesCount")
	@Order(value=0)
	public MaximumUnpaidItemStrikesCountDetailsType maximumUnpaidItemStrikesCount;	
	
	@Element(name = "MaximumUnpaidItemStrikesDuration")
	@Order(value=1)
	public List<MaximumUnpaidItemStrikesDurationDetailsType> maximumUnpaidItemStrikesDuration;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
    
}