// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

public enum MessageTypeCodeType {

    /**
     * 
   *             Member to Member message initiated by bidder/potential bidder
   *             to a seller of a particular item.
   *           
     */
    ASK_SELLER_QUESTION("AskSellerQuestion"),
  

    /**
     * 
   *             Member to Member message initiated as a response
   *             to an Ask A Question message.
   *           
     */
    RESPONSE_TO_ASQ_QUESTION("ResponseToASQQuestion"),
  

    /**
     * 
   *             Member to Member message initiated by any eBay member
   *             to another eBay member.
   *           
     */
    CONTACT_EBAY_MEMBER("ContactEbayMember"),
  

    /**
     * 
   *             Member message between order partners within 90 days
   *             after creation of the order.
   *           
     */
    CONTACT_TRANSACTION_PARTNER("ContactTransactionPartner"),
  

    /**
     * 
   *             Member to Member message initiated as a response
   *             to a Contact eBay Member message.
   *           
     */
    RESPONSE_TO_CONTACTE_BAY_MEMBER("ResponseToContacteBayMember"),
  

    /**
     * 
   *             Member to Member message initiated by any eBay member
   *             to another eBay member who has posted on a community forum
   *             within the past 7 days.
   *           
     */
    CONTACTE_BAY_MEMBER_VIA_COMMUNITY_LINK("ContacteBayMemberViaCommunityLink"),
  

    /**
     * 
   *             Reserved for future or internal use.
   *           
     */
    CUSTOM_CODE("CustomCode"),
  

    /**
     * 
   *             All message types.
   *           
     */
    ALL("All"),
  

    /**
     * 
   *             Member to Member message initiated by sellers to their
   *             bidders during an active listing.
   *           
     */
    CONTACT_MY_BIDDER("ContactMyBidder"),
  

    /**
     * 
   *             Member message initiated after eBay receives an email sent by an
   *             eBay member's email client to another eBay member.
   *           
     */
    CONTACTE_BAY_MEMBER_VIA_ANONYMOUS_EMAIL("ContacteBayMemberViaAnonymousEmail"),
  

    /**
     * 
   *              Indicates that an inquiry has been sent to the seller regarding the
   *  corresponding classified ad listing.
   *  
     */
    CLASSIFIEDS_CONTACT_SELLER("ClassifiedsContactSeller"),
  

    /**
     * 
   * Indicates that a best offer has been made on the seller's corresponding
   * classified ad listing. This message type is only applicable to Classified
   * categories that allow the Best Offer feature, such as motor vehicles.
   *  
     */
    CLASSIFIEDS_BEST_OFFER("ClassifiedsBestOffer");
  
  
    private final String value;
  
    MessageTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static MessageTypeCodeType fromValue(String v) {
        if (v != null) {
            for (MessageTypeCodeType c: MessageTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}