// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *    This type provides information about the shipping service, cost, address, and delivery estimates for the domestic leg of a Global Shipping Program shipment.
 * 
 */
public class MultiLegShipmentType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ShippingServiceDetails")
	@Order(value=0)
	public MultiLegShippingServiceType shippingServiceDetails;	
	
	@Element(name = "ShipToAddress")
	@Order(value=1)
	public AddressType shipToAddress;	
	
	@Element(name = "ShippingTimeMin")
	@Order(value=2)
	public Integer shippingTimeMin;	
	
	@Element(name = "ShippingTimeMax")
	@Order(value=3)
	public Integer shippingTimeMax;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}