// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Information about a single notification. Notification information includes
 * the reference ID, notification type, current status, time delivered, error code,
 * and error message for the notification. If notification details are included in
 * the response, all of the detail fields are returned.
 * 
 */
public class NotificationDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "DeliveryURL")
	@Order(value=0)
	public String deliveryURL;	
	
	@Element(name = "ReferenceID")
	@Order(value=1)
	public String referenceID;	
	
	@Element(name = "ExpirationTime")
	@Order(value=2)
	public Date expirationTime;	
	
	@Element(name = "Type")
	@Order(value=3)
	public NotificationEventTypeCodeType type;	
	
	@Element(name = "Retries")
	@Order(value=4)
	public Integer retries;	
	
	@Element(name = "DeliveryStatus")
	@Order(value=5)
	public NotificationEventStateCodeType deliveryStatus;	
	
	@Element(name = "NextRetryTime")
	@Order(value=6)
	public Date nextRetryTime;	
	
	@Element(name = "DeliveryTime")
	@Order(value=7)
	public Date deliveryTime;	
	
	@Element(name = "ErrorMessage")
	@Order(value=8)
	public String errorMessage;	
	
	@Element(name = "DeliveryURLName")
	@Order(value=9)
	public String deliveryURLName;	
	
	@AnyElement
	@Order(value=10)
	public List<Object> any;	
	
    
}