// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *  This type is deprecated as Pictures Manager was retired.
 * 
 * 
 */
public class PictureManagerFolderType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "FolderID")
	@Order(value=0)
	public Integer folderID;	
	
	@Element(name = "Name")
	@Order(value=1)
	public String name;	
	
	@Element(name = "Picture")
	@Order(value=2)
	public List<PictureManagerPictureType> picture;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}