// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Enables the authenticated user to to make a bid, a best offer, or
 * a purchase on the item specified by the ItemID input field.
 * 
 */
@RootElement(name = "PlaceOfferRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class PlaceOfferRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Offer")
	@Order(value=0)
	public OfferType offer;	
	
	@Element(name = "ItemID")
	@Order(value=1)
	public String itemID;	
	
	@Element(name = "BlockOnWarning")
	@Order(value=2)
	public Boolean blockOnWarning;	
	
	@Element(name = "AffiliateTrackingDetails")
	@Order(value=3)
	public AffiliateTrackingDetailsType affiliateTrackingDetails;	
	
	@Element(name = "VariationSpecifics")
	@Order(value=4)
	public NameValueListArrayType variationSpecifics;	
	
    
}