// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * This type is deprecated as <b>GetProduct*</b> calls were deprecated.
 * 
 * 
 */
public class ProductSearchResultType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ID")
	@Order(value=0)
	public String id;	
	
	@Element(name = "NumProducts")
	@Order(value=1)
	public String numProducts;	
	
	@Element(name = "AttributeSet")
	@Order(value=2)
	public List<ResponseAttributeSetType> attributeSet;	
	
	@Element(name = "DisplayStockPhotos")
	@Order(value=3)
	public Boolean displayStockPhotos;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}