// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import com.leansoft.nano.custom.types.Duration;
import java.util.List;

/**
 * 
 * This type is deprecated as Cross Promotions are no longer supported in the APIs.
 * 
 * 
 */
public class PromotedItemType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "PictureURL")
	@Order(value=1)
	public String pictureURL;	
	
	@Element(name = "Position")
	@Order(value=2)
	public Integer position;	
	
	@Element(name = "SelectionType")
	@Order(value=3)
	public PromotionItemSelectionCodeType selectionType;	
	
	@Element(name = "Title")
	@Order(value=4)
	public String title;	
	
	@Element(name = "ListingType")
	@Order(value=5)
	public ListingTypeCodeType listingType;	
	
	@Element(name = "PromotionDetails")
	@Order(value=6)
	public List<PromotionDetailsType> promotionDetails;	
	
	@Element(name = "TimeLeft")
	@Order(value=7)
	public Duration timeLeft;	
	
	@AnyElement
	@Order(value=8)
	public List<Object> any;	
	
    
}