// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * Values specify or indicate the type of promotional sale offered.
 * Promotional sales give store owners the ability to apply discounts and/or
 * free shipping across many listings for a specific duration.
 * 
 */
public enum PromotionalSaleTypeCodeType {

    /**
     * 
   * Sale offers price discount only.
   * 
     */
    PRICE_DISCOUNT_ONLY("PriceDiscountOnly"),
  

    /**
     * 
   * Sale offers free shipping only.
   * 
     */
    FREE_SHIPPING_ONLY("FreeShippingOnly"),
  

    /**
     * 
   * Sale offers both price discount and free shipping.
   * 
     */
    PRICE_DISCOUNT_AND_FREE_SHIPPING("PriceDiscountAndFreeShipping"),
  

    /**
     * 
   * Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    PromotionalSaleTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static PromotionalSaleTypeCodeType fromValue(String v) {
        if (v != null) {
            for (PromotionalSaleTypeCodeType c: PromotionalSaleTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}