// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * This type is deprecated as Cross Promotions are no longer supported in the APIs.
 * 
 * 
 */
public enum PromotionSchemeCodeType {

    /**
     * 
   * 
   * The seller specifies individual items in the store that are
   * promoted when a buyer views, bids on, or purchases a store item.
   * 
     */
    ITEM_TO_ITEM("ItemToItem"),
  

    /**
     * 
   * 
   * The seller specifies a store category from which items are promoted
   * when a buyer views, bids on, or purchases an individual item in the store.
   * 
     */
    ITEM_TO_STORE_CAT("ItemToStoreCat"),
  

    /**
     * 
   * 
   * The seller specifies referring and promoted categories, both from
   * the store. When a buyer views or acts on any item from that category, items
   * from the promoted category are also displayed.
   * 
     */
    STORE_TO_STORE_CAT("StoreToStoreCat"),
  

    /**
     * 
   * 
   * The seller specifies a referring item and defines promoted items
   * selected from a store category, eBay category, or keywords.
   * 
     */
    ITEM_TO_DEFAULT_RULE("ItemToDefaultRule"),
  

    /**
     * 
   * 
   * The seller specifies a store category or eBay category, with
   * optional keywords, for referring items and one for promoted items. When a
   * referring item is selected from the category and keywords, items from the
   * promoted category and keywords are also displayed.
   * 
     */
    DEFAULT_RULE("DefaultRule"),
  

    /**
     * 
   * 
   * This scheme is returned as a backfill scheme used to promote items.
   * 
     */
    CATEGORY_PROXIMITY("CategoryProximity"),
  

    /**
     * 
   * 
   * This scheme is returned as related category scheme used to promote
   * items.
   * 
     */
    RELATED_CATEGORY_RULE("RelatedCategoryRule"),
  

    /**
     * 
   * 
   * This scheme is returned as a backfill scheme used to promote items.
   * 
     */
    DEFAULT_UP_SELL_LOGIC("DefaultUpSellLogic"),
  

    /**
     * 
   * 
   * This scheme is returned as a backfill scheme used to promote items.
   * 
     */
    DEFAULT_CROSS_SELL_LOGIC("DefaultCrossSellLogic"),
  

    /**
     * 
   * 
   * Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    PromotionSchemeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static PromotionSchemeCodeType fromValue(String v) {
        if (v != null) {
            for (PromotionSchemeCodeType c: PromotionSchemeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}