// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

public enum QuestionTypeCodeType {

    /**
     * 
   *   General questions about the item.
   *   
     */
    GENERAL("General"),
  

    /**
     * 
   *  Questions related to the shipping of the item.
   * 
     */
    SHIPPING("Shipping"),
  

    /**
     * 
   * Questions related to the payment for the item.
   * 
     */
    PAYMENT("Payment"),
  

    /**
     * 
   * Questions related to the shipping of this item
   * bundled with other items also purchased on eBay.
   * 
     */
    MULTIPLE_ITEM_SHIPPING("MultipleItemShipping"),
  

    /**
     * 
   * Customized subjects set by the seller using
   * SetMessagePreferences or the eBay Web site.
   * 
     */
    CUSTOMIZED_SUBJECT("CustomizedSubject"),
  

    /**
     * 
   * No question type applies. This value
   * doesn't apply to AddMemberMessageAAQToPartner.
   * Note that the value of None can apply if
   * Messages.Message.MessageType isn't set to AskSellerQuestion.
   * 
     */
    NONE("None"),
  

    /**
     * 
   * Reserved for future or internal use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    QuestionTypeCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static QuestionTypeCodeType fromValue(String v) {
        if (v != null) {
            for (QuestionTypeCodeType c: QuestionTypeCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}