// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 *  Container consisting of one or more RefundFundingSource containers.
 * 
 */
public class RefundFundingSourceArrayType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "RefundFundingSource")
	@Order(value=0)
	public List<RefundFundingSourceType> refundFundingSource;	
	
	@AnyElement
	@Order(value=1)
	public List<Object> any;	
	
    
}