// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Enables a seller to change the properties of a currently active listing.&nbsp;<b>Also for Half.com</b>.
 * <br>
 * <br>
 * After one item in a multi-quantity fixed-price listing has been sold, you can not
 * the values in the Title, Primary Category, Secondary Category, Listing Duration,
 * and Listing Type fields for that listing. However, all other fields in the
 * multi-quantity, fixed-price listing are editable.
 * <br>
 * <br>
 * Inputs are the Item ID of the listing you are revising, and the field or fields
 * that you are updating.
 * 
 */
@RootElement(name = "ReviseItemRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class ReviseItemRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Item")
	@Order(value=0)
	public ItemType item;	
	
	@Element(name = "DeletedField")
	@Order(value=1)
	public List<String> deletedField;	
	
	@Element(name = "VerifyOnly")
	@Order(value=2)
	public Boolean verifyOnly;	
	
    
}