// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Contains data indicating whether an item has been revised since the
 * listing became active and, if so, which among a subset of properties
 * have been changed by the revision.
 * Output only.
 * 
 */
public class ReviseStatusType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemRevised")
	@Order(value=0)
	public boolean itemRevised;	
	
	@Element(name = "BuyItNowAdded")
	@Order(value=1)
	public Boolean buyItNowAdded;	
	
	@Element(name = "BuyItNowLowered")
	@Order(value=2)
	public Boolean buyItNowLowered;	
	
	@Element(name = "ReserveLowered")
	@Order(value=3)
	public Boolean reserveLowered;	
	
	@Element(name = "ReserveRemoved")
	@Order(value=4)
	public Boolean reserveRemoved;	
	
	@AnyElement
	@Order(value=5)
	public List<Object> any;	
	
    
}