// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Provides information about the visibility level you've earned for your eBay listings.
 * When you have a better search standing, your listings may receive higher
 * placement in Best Match search results.
 * 
 */
public class SearchStandingDashboardType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Status")
	@Order(value=0)
	public SearchStandingStatusCodeType status;	
	
	@AnyElement
	@Order(value=1)
	public List<Object> any;	
	
    
}