// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type that defines the <b>SellerDiscount</b> container, which contains the ID,
 * name, and amount of the seller discount.
 * 
 */
public class SellerDiscountType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "CampaignID")
	@Order(value=0)
	public Long campaignID;	
	
	@Element(name = "CampaignDisplayName")
	@Order(value=1)
	public String campaignDisplayName;	
	
	@Element(name = "ItemDiscountAmount")
	@Order(value=2)
	public AmountType itemDiscountAmount;	
	
	@Element(name = "ShippingDiscountAmount")
	@Order(value=3)
	public AmountType shippingDiscountAmount;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}