// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Changes the category structure of an eBay store.
 * 
 */
@RootElement(name = "SetStoreCategoriesRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetStoreCategoriesRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Action")
	@Order(value=0)
	public StoreCategoryUpdateActionCodeType action;	
	
	@Element(name = "ItemDestinationCategoryID")
	@Order(value=1)
	public Long itemDestinationCategoryID;	
	
	@Element(name = "DestinationParentCategoryID")
	@Order(value=2)
	public Long destinationParentCategoryID;	
	
	@Element(name = "StoreCategories")
	@Order(value=3)
	public StoreCustomCategoryArrayType storeCategories;	
	
    
}