// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Sets the preferences for a user's eBay Store.
 * 
 */
@RootElement(name = "SetStorePreferencesRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class SetStorePreferencesRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "StorePreferences")
	@Order(value=0)
	public StorePreferencesType storePreferences;	
	
    
}