// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * The current state of user SMS subscription.
 * 
 */
public enum SMSSubscriptionUserStatusCodeType {

    /**
     * 
   * (out) Registered.
   * 
     */
    REGISTERED("Registered"),
  

    /**
     * 
   * (out) Unregistered.
   * 
     */
    UNREGISTERED("Unregistered"),
  

    /**
     * 
   * (out) Pending subscription.
   * 
     */
    PENDING("Pending"),
  

    /**
     * 
   * (out) Subscription failed.
   * 
     */
    FAILED("Failed"),
  

    /**
     * 
   * (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    SMSSubscriptionUserStatusCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static SMSSubscriptionUserStatusCodeType fromValue(String v) {
        if (v != null) {
            for (SMSSubscriptionUserStatusCodeType c: SMSSubscriptionUserStatusCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}