// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Store logo.
 * 
 */
public class StoreLogoType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "LogoID")
	@Order(value=0)
	public Integer logoID;	
	
	@Element(name = "Name")
	@Order(value=1)
	public String name;	
	
	@Element(name = "URL")
	@Order(value=2)
	public String url;	
	
	@AnyElement
	@Order(value=3)
	public List<Object> any;	
	
    
}