// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * Specifies the type of link in the custom listing header.
 * 
 */
public enum StoreCustomListingHeaderLinkCodeType {

    /**
     * 
   * No type.
   * 
     */
    NONE("None"),
  

    /**
     * 
   * Link is to an About Me page.
   * 
     */
    ABOUT_ME_PAGE("AboutMePage"),
  

    /**
     * 
   * Link is to a custom page.
   * 
     */
    CUSTOM_PAGE("CustomPage"),
  

    /**
     * 
   * Link is to a custom category.
   * 
     */
    CUSTOM_CATEGORY("CustomCategory"),
  

    /**
     * 
   *    (out) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode");
  
  
    private final String value;
  
    StoreCustomListingHeaderLinkCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static StoreCustomListingHeaderLinkCodeType fromValue(String v) {
        if (v != null) {
            for (StoreCustomListingHeaderLinkCodeType c: StoreCustomListingHeaderLinkCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}