// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

/**
 * 
 * (in) Indicates the type of string matching to use
 * when a value is submitted in CharityName. If no value is
 * specified, default behavior is "StartsWith." Does not
 * apply to Query.
 * 
 */
public enum StringMatchCodeType {

    /**
     * 
   * (in) Reserved for internal or future use.
   * 
     */
    CUSTOM_CODE("CustomCode"),
  

    /**
     * 
   * (in) Matches strings that begin with the submitted
   * value. For example, submitting a CharityName value
   * of "heart" matches "Heart of Gold," but not "Open
   * Hearts." Default behavior if no value is
   * specified.
   * 
     */
    STARTS_WITH("StartsWith"),
  

    /**
     * 
   * (in) Matches strings that contain the submitted
   * value. For example, submitting a CharityName value
   * of "heart" matches both "Heart of Gold" and "Open
   * Hearts."
   * 
     */
    CONTAINS("Contains");
  
  
    private final String value;
  
    StringMatchCodeType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static StringMatchCodeType fromValue(String v) {
        if (v != null) {
            for (StringMatchCodeType c: StringMatchCodeType.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}