// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Type defining the <b>TicketListingDetails</b> container, which is used in
 * an Add/Revise/Relist call to provide more details about event tickets.
 * 
 */
public class TicketListingDetailsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "EventTitle")
	@Order(value=0)
	public String eventTitle;	
	
	@Element(name = "Venue")
	@Order(value=1)
	public String venue;	
	
	@Element(name = "PrintedDate")
	@Order(value=2)
	public String printedDate;	
	
	@Element(name = "PrintedTime")
	@Order(value=3)
	public String printedTime;	
	
	@AnyElement
	@Order(value=4)
	public List<Object> any;	
	
    
}