// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * 
 * Specifies the Date range.
 * 
 */
public class TimeRangeType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "TimeFrom")
	@Order(value=0)
	public Date timeFrom;	
	
	@Element(name = "TimeTo")
	@Order(value=1)
	public Date timeTo;	
	
	@AnyElement
	@Order(value=2)
	public List<Object> any;	
	
    
}