// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Simulates the creation of a new Second Chance Offer
 * listing of an item without actually creating a listing.
 * 
 */
@RootElement(name = "VerifyAddSecondChanceItemRequest", namespace = "urn:ebay:apis:eBLBaseComponents")
public class VerifyAddSecondChanceItemRequestType extends AbstractRequestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "RecipientBidderUserID")
	@Order(value=0)
	public String recipientBidderUserID;	
	
	@Element(name = "BuyItNowPrice")
	@Order(value=1)
	public AmountType buyItNowPrice;	
	
	@Element(name = "Duration")
	@Order(value=2)
	public SecondChanceOfferDurationCodeType duration;	
	
	@Element(name = "ItemID")
	@Order(value=3)
	public String itemID;	
	
	@Element(name = "SellerMessage")
	@Order(value=4)
	public String sellerMessage;	
	
    
}