// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * 
 * Type defining the <b>VerifiedUserRequirements</b> container, which is used by the
 * seller to block prospective buyers who do not pass a verified user check. Verified users are
 * applicable to the Australia, France, India, Ireland, Spain, and UK sites.
 * 
 */
public class VerifiedUserRequirementsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "VerifiedUser")
	@Order(value=0)
	public Boolean verifiedUser;	
	
	@Element(name = "MinimumFeedbackScore")
	@Order(value=1)
	public Integer minimumFeedbackScore;	
	
    
}