// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.api.trading;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Returns the estimated fees that would be applicable for a new listing
 * (were the item actually listed to eBay with AddItem).
 * 
 */
@RootElement(name = "VerifyAddItemResponse", namespace = "urn:ebay:apis:eBLBaseComponents")
public class VerifyAddItemResponseType extends AbstractResponseType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "ItemID")
	@Order(value=0)
	public String itemID;	
	
	@Element(name = "Fees")
	@Order(value=1)
	public FeesType fees;	
	
	@Element(name = "ExpressListing")
	@Order(value=2)
	public Boolean expressListing;	
	
	@Element(name = "ExpressItemRequirements")
	@Order(value=3)
	public ExpressItemRequirementsType expressItemRequirements;	
	
	@Element(name = "CategoryID")
	@Order(value=4)
	public String categoryID;	
	
	@Element(name = "Category2ID")
	@Order(value=5)
	public String category2ID;	
	
	@Element(name = "DiscountReason")
	@Order(value=6)
	public List<DiscountReasonCodeType> discountReason;	
	
	@Element(name = "ProductSuggestions")
	@Order(value=7)
	public ProductSuggestionsType productSuggestions;	
	
    
}