// Generated by wsdl compiler for android/java
// DO NOT CHANGE!
package com.ebay.finding.api.client;


import com.leansoft.nano.ws.ServiceCallback;
import com.leansoft.nano.ws.NanoXMLClient;
import com.ebay.finding.api.GetHistogramsResponse;
import com.ebay.finding.api.GetSearchKeywordsRecommendationResponse;
import com.ebay.finding.api.FindItemsForFavoriteSearchResponse;
import com.ebay.finding.api.FindItemsAdvancedRequest;
import com.ebay.finding.api.FindItemsByImageResponse;
import com.ebay.finding.api.FindItemsAdvancedResponse;
import com.ebay.finding.api.GetHistogramsRequest;
import com.ebay.finding.api.FindItemsIneBayStoresRequest;
import com.ebay.finding.api.FindItemsForFavoriteSearchRequest;
import com.ebay.finding.api.FindCompletedItemsResponse;
import com.ebay.finding.api.FindItemsByKeywordsResponse;
import com.ebay.finding.api.FindItemsByProductRequest;
import com.ebay.finding.api.FindItemsByCategoryRequest;
import com.ebay.finding.api.FindItemsByImageRequest;
import com.ebay.finding.api.GetVersionResponse;
import com.ebay.finding.api.FindItemsIneBayStoresResponse;
import com.ebay.finding.api.FindItemsByProductResponse;
import com.ebay.finding.api.FindItemsByCategoryResponse;
import com.ebay.finding.api.GetVersionRequest;
import com.ebay.finding.api.GetSearchKeywordsRecommendationRequest;
import com.ebay.finding.api.FindCompletedItemsRequest;
import com.ebay.finding.api.FindItemsByKeywordsRequest;


/**
 This class is the XML client to the FindingServicePortType Web Service.
*/ 
public class FindingServicePortType_XMLClient extends NanoXMLClient {


    /**
     public method
    */
    public void getSearchKeywordsRecommendation(GetSearchKeywordsRecommendationRequest requestObject, ServiceCallback<GetSearchKeywordsRecommendationResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetSearchKeywordsRecommendationResponse.class);
    }

    /**
     public method
    */
    public void findItemsByKeywords(FindItemsByKeywordsRequest requestObject, ServiceCallback<FindItemsByKeywordsResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsByKeywordsResponse.class);
    }

    /**
     public method
    */
    public void findItemsByCategory(FindItemsByCategoryRequest requestObject, ServiceCallback<FindItemsByCategoryResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsByCategoryResponse.class);
    }

    /**
     public method
    */
    public void findItemsAdvanced(FindItemsAdvancedRequest requestObject, ServiceCallback<FindItemsAdvancedResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsAdvancedResponse.class);
    }

    /**
     public method
    */
    public void findItemsByProduct(FindItemsByProductRequest requestObject, ServiceCallback<FindItemsByProductResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsByProductResponse.class);
    }

    /**
     public method
    */
    public void findItemsIneBayStores(FindItemsIneBayStoresRequest requestObject, ServiceCallback<FindItemsIneBayStoresResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsIneBayStoresResponse.class);
    }

    /**
     public method
    */
    public void findItemsByImage(FindItemsByImageRequest requestObject, ServiceCallback<FindItemsByImageResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsByImageResponse.class);
    }

    /**
     public method
    */
    public void getHistograms(GetHistogramsRequest requestObject, ServiceCallback<GetHistogramsResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetHistogramsResponse.class);
    }

    /**
     public method
    */
    public void findCompletedItems(FindCompletedItemsRequest requestObject, ServiceCallback<FindCompletedItemsResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindCompletedItemsResponse.class);
    }

    /**
     public method
    */
    public void getVersion(GetVersionRequest requestObject, ServiceCallback<GetVersionResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, GetVersionResponse.class);
    }

    /**
     public method
    */
    public void findItemsForFavoriteSearch(FindItemsForFavoriteSearchRequest requestObject, ServiceCallback<FindItemsForFavoriteSearchResponse> serviceCallback) {
       
        
        super.invoke(requestObject, serviceCallback, FindItemsForFavoriteSearchResponse.class);
    }


}