// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Information regarding an error or warning that occurred when eBay processed
 * the request. Not returned when the ack value is Success. Run-time errors are
 * not reported here, but are instead reported as part of a SOAP fault.
 * 
 */
public class ErrorMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public List<ErrorData> error;	
	
    
}