// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.ebay.marketplace.search.v1.services;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * 
 * Use findItemsIneBayStores to find items listed in eBay stores. Specify
 * storeName in the request to retrieve all listings within a single store. You
 * can combine storeName with keywords to find specific items, or use keywords
 * without storeName to search for items in all eBay stores.
 * <br><br>
 * Search results can be filtered by item details or aspects and sorted by a
 * variety of criteria.
 * 
 */
@RootElement(name = "findItemsIneBayStoresRequest", namespace = "http://www.ebay.com/marketplace/search/v1/services")
public class FindItemsIneBayStoresRequest extends BaseFindingServiceRequest implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	@Order(value=0)
	public String keywords;	
	
	@Element
	@Order(value=1)
	public String storeName;	
	
	@Element
	@Order(value=2)
	public List<ItemFilter> itemFilter;	
	
	@Element
	@Order(value=3)
	public List<OutputSelectorType> outputSelector;	
	
	@Element
	@Order(value=4)
	public List<AspectFilter> aspectFilter;	
	
	@Element
	@Order(value=5)
	public List<DomainFilter> domainFilter;	
	
	@Element
	@Order(value=6)
	public List<String> categoryId;	
	
    
}